"""Unit tests for the roomba_plus.clean_room action helpers.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home

Tests the three pure-Python helpers in __init__.py:
  - _resolve_pmapv_id: live pmap freshness lookup
  - _resolve_rooms: name→region_id resolver with cross-floor guard
  - Command params shape built by _async_handle_clean_room logic

No HA or roombapy installation required — uses the stubs from conftest.py.
"""
import sys
import os
import pytest

ROOT = os.path.join(os.path.dirname(__file__), "..")
sys.path.insert(0, ROOT)

# Constants are defined directly here to avoid importing the package __init__
# which pulls in HA and roombapy. The values must match const.py exactly.
CONF_SMART_ZONE_DATA = "smart_zone_data"
SERVICE_CLEAN_ROOM = "clean_room"
ATTR_ROOM_NAME = "room_name"
ATTR_ORDERED = "ordered"


# ── Inline reimplementation for isolated unit testing ─────────────────────────
# These mirror the production helpers exactly so we can test the logic without
# importing the full __init__ module (which pulls in HA internals).

class ServiceValidationError(Exception):
    def __init__(self, message, translation_domain=None, translation_key=None, translation_placeholders=None):
        super().__init__(message)
        self.translation_key = translation_key
        self.translation_placeholders = translation_placeholders or {}


def _resolve_pmapv_id(state: dict, pmap_id: str):
    for pmap in state.get("pmaps", []):
        if pmap_id in pmap:
            return pmap[pmap_id]
    return None


def _resolve_rooms(zone_data: dict, room_names: list):
    index = {
        meta["name"].casefold(): (rid, meta["pmap_id"])
        for rid, meta in zone_data.items()
        if meta.get("name") and meta.get("pmap_id")
    }
    resolved = []
    unknown = []
    for name in room_names:
        match = index.get(name.casefold())
        if match is None:
            unknown.append(name)
        else:
            resolved.append(match)
    if unknown:
        raise ServiceValidationError(
            f"Unknown room(s): {', '.join(unknown)}",
            translation_key="rooms_not_found",
            translation_placeholders={"names": ", ".join(unknown)},
        )
    pmap_ids = {p for _, p in resolved}
    if len(pmap_ids) > 1:
        raise ServiceValidationError(
            "Rooms span multiple floors",
            translation_key="rooms_different_floors",
            translation_placeholders={"pmap_ids": ", ".join(pmap_ids)},
        )
    return resolved


# ── _resolve_pmapv_id ─────────────────────────────────────────────────────────

class TestResolvePmapvId:
    def test_found_single_pmap(self):
        state = {"pmaps": [{"abc123": "220101T120000"}]}
        assert _resolve_pmapv_id(state, "abc123") == "220101T120000"

    def test_found_among_multiple_pmaps(self):
        state = {"pmaps": [{"floor1": "ts1"}, {"floor2": "ts2"}]}
        assert _resolve_pmapv_id(state, "floor2") == "ts2"

    def test_not_found_returns_none(self):
        state = {"pmaps": [{"abc123": "ts1"}]}
        assert _resolve_pmapv_id(state, "does_not_exist") is None

    def test_empty_pmaps_returns_none(self):
        assert _resolve_pmapv_id({"pmaps": []}, "abc123") is None

    def test_missing_pmaps_key_returns_none(self):
        assert _resolve_pmapv_id({}, "abc123") is None

    def test_always_reads_latest_value(self):
        """Simulates a map retrain: pmapv_id changes, resolver reflects it."""
        state_v1 = {"pmaps": [{"abc123": "220101T120000"}]}
        state_v2 = {"pmaps": [{"abc123": "230601T090000"}]}
        assert _resolve_pmapv_id(state_v1, "abc123") == "220101T120000"
        assert _resolve_pmapv_id(state_v2, "abc123") == "230601T090000"


# ── _resolve_rooms ────────────────────────────────────────────────────────────

ZONE_DATA = {
    "3": {"name": "Kitchen", "pmap_id": "map_ground_floor"},
    "5": {"name": "Hallway", "pmap_id": "map_ground_floor"},
    "7": {"name": "Office",  "pmap_id": "map_ground_floor"},
    "9": {"name": "Bedroom", "pmap_id": "map_first_floor"},
}


class TestResolveRooms:
    def test_single_room(self):
        result = _resolve_rooms(ZONE_DATA, ["Kitchen"])
        assert result == [("3", "map_ground_floor")]

    def test_multi_room_same_floor(self):
        result = _resolve_rooms(ZONE_DATA, ["Kitchen", "Hallway"])
        assert result == [("3", "map_ground_floor"), ("5", "map_ground_floor")]

    def test_order_preserved(self):
        result = _resolve_rooms(ZONE_DATA, ["Office", "Kitchen"])
        assert result == [("7", "map_ground_floor"), ("3", "map_ground_floor")]

    def test_case_insensitive(self):
        result = _resolve_rooms(ZONE_DATA, ["kitchen"])
        assert result == [("3", "map_ground_floor")]

    def test_mixed_case(self):
        result = _resolve_rooms(ZONE_DATA, ["KITCHEN", "halLWAY"])
        assert result == [("3", "map_ground_floor"), ("5", "map_ground_floor")]

    def test_unknown_room_raises(self):
        with pytest.raises(ServiceValidationError) as exc_info:
            _resolve_rooms(ZONE_DATA, ["Bathroom"])
        assert exc_info.value.translation_key == "rooms_not_found"
        assert "Bathroom" in exc_info.value.translation_placeholders["names"]

    def test_partial_unknown_raises(self):
        with pytest.raises(ServiceValidationError) as exc_info:
            _resolve_rooms(ZONE_DATA, ["Kitchen", "Nonexistent"])
        assert "Nonexistent" in exc_info.value.translation_placeholders["names"]

    def test_multiple_unknowns_all_reported(self):
        with pytest.raises(ServiceValidationError) as exc_info:
            _resolve_rooms(ZONE_DATA, ["X", "Y"])
        names = exc_info.value.translation_placeholders["names"]
        assert "X" in names
        assert "Y" in names

    def test_cross_floor_raises(self):
        with pytest.raises(ServiceValidationError) as exc_info:
            _resolve_rooms(ZONE_DATA, ["Kitchen", "Bedroom"])
        assert exc_info.value.translation_key == "rooms_different_floors"
        placeholders = exc_info.value.translation_placeholders["pmap_ids"]
        assert "map_ground_floor" in placeholders
        assert "map_first_floor" in placeholders

    def test_empty_zone_data_raises(self):
        with pytest.raises(ServiceValidationError):
            _resolve_rooms({}, ["Kitchen"])

    def test_empty_room_list_returns_empty(self):
        result = _resolve_rooms(ZONE_DATA, [])
        assert result == []

    def test_regions_payload_shape(self):
        """Verify the regions list shape expected by the MQTT command."""
        resolved = _resolve_rooms(ZONE_DATA, ["Kitchen", "Hallway"])
        regions = [{"region_id": rid, "type": "rid"} for rid, _ in resolved]
        assert regions == [
            {"region_id": "3", "type": "rid"},
            {"region_id": "5", "type": "rid"},
        ]

    def test_zone_data_missing_name_skipped(self):
        """Entries without a name or pmap_id are not matchable."""
        data = {
            "3": {"name": "Kitchen", "pmap_id": "map_a"},
            "4": {"pmap_id": "map_a"},       # missing name
            "5": {"name": "Office"},          # missing pmap_id
        }
        result = _resolve_rooms(data, ["Kitchen"])
        assert result == [("3", "map_a")]
        # Zone 4 and 5 are not in the index
        with pytest.raises(ServiceValidationError):
            _resolve_rooms(data, ["Office"])


# ── Command params shape ──────────────────────────────────────────────────────

class TestCommandParams:
    """Verify the params dict passed to send_command is correctly formed."""

    def _build_params(self, resolved, pmap_id, user_pmapv_id, ordered=True):
        return {
            "ordered": 1 if ordered else 0,
            "pmap_id": pmap_id,
            "user_pmapv_id": user_pmapv_id,
            "regions": [
                {"region_id": rid, "type": "rid"}
                for rid, _ in resolved
            ],
        }

    def test_single_room_params(self):
        resolved = [("3", "map_a")]
        params = self._build_params(resolved, "map_a", "ts_fresh")
        assert params["pmap_id"] == "map_a"
        assert params["user_pmapv_id"] == "ts_fresh"
        assert params["ordered"] == 1
        assert params["regions"] == [{"region_id": "3", "type": "rid"}]

    def test_multi_room_params(self):
        resolved = [("3", "map_a"), ("5", "map_a")]
        params = self._build_params(resolved, "map_a", "ts_fresh")
        assert len(params["regions"]) == 2
        assert params["regions"][0] == {"region_id": "3", "type": "rid"}
        assert params["regions"][1] == {"region_id": "5", "type": "rid"}

    def test_ordered_false_sends_zero(self):
        resolved = [("3", "map_a"), ("5", "map_a")]
        params = self._build_params(resolved, "map_a", "ts", ordered=False)
        assert params["ordered"] == 0

    def test_ordered_true_sends_one(self):
        resolved = [("3", "map_a")]
        params = self._build_params(resolved, "map_a", "ts", ordered=True)
        assert params["ordered"] == 1

    def test_pmap_id_from_first_resolved(self):
        """pmap_id in params must come from the resolved tuple, not a separate lookup."""
        resolved = [("3", "map_ground"), ("5", "map_ground")]
        pmap_id = resolved[0][1]
        params = self._build_params(resolved, pmap_id, "ts")
        assert params["pmap_id"] == "map_ground"
