"""REST API view for Roomba+ -- mission history endpoint.

GET /api/roomba_plus/{entry_id}/mission_history

Query parameters:
  days:   int  (1-90, default 28)   -- lookback window for day-summary format
  format: str  ("summary" | "records", default "summary")
            summary  -- day-aggregated DaySummary array (v0.1-beta card format,
                        always available, sourced from local MissionStore)
            records  -- per-mission array (v1.0 card format, sourced from cloud
                        raw_records when available, falls back to local
                        MissionStore records for robots without cloud credentials)

v2.1 changes:
  F4a -- zone names injected into cloud records (120 s timestamp tolerance)
  F7o -- startup race guard (503), coordinator failure (503), unknown format (400)

Registered once per HA instance (sentinel guard in __init__.py).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import datetime
import logging
from typing import TYPE_CHECKING, Any

from aiohttp import web
from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant

from .const import DOMAIN

if TYPE_CHECKING:
    from .models import RoombaData

_LOGGER = logging.getLogger(__name__)

# F7o -- valid format values; unknown values return 400
_VALID_FORMATS = {"summary", "records", "hazards"}


def _build_local_zones_index(mission_store_records: list[dict]) -> dict[int, list[str]]:
    """Build a ts -> zone-names index from local MissionStore records.

    F4a -- used to inject zone names into cloud records which carry zones=[].
    Keys are integer Unix timestamps of ended_at. Tolerance matching is done
    at the call site (120 s window).
    """
    index: dict[int, list[str]] = {}
    for r in mission_store_records:
        ended_str = r.get("ended_at", "")
        zones = r.get("zones") or []
        if not ended_str or not zones:
            continue
        try:
            ended_dt = datetime.datetime.fromisoformat(ended_str)
        except (ValueError, TypeError):
            continue
        if ended_dt.tzinfo is None:
            ended_dt = ended_dt.replace(tzinfo=datetime.timezone.utc)
        index[int(ended_dt.timestamp())] = list(zones)
    return index


def _inject_zones(
    record: dict[str, Any],
    local_zones_index: dict[int, list[str]],
    tolerance_sec: int = 120,
) -> dict[str, Any]:
    """Return record with zones populated from local MissionStore when available.

    F4a -- matches on the cloud record's ended_at ISO string against the
    local ended_at index within tolerance_sec.  If a match is found and the
    local record has zone names, they replace the empty zones list.
    """
    end_ts_str = record.get("ended_at")
    if not end_ts_str or not local_zones_index:
        return record

    try:
        end_dt = datetime.datetime.fromisoformat(end_ts_str)
        if end_dt.tzinfo is None:
            end_dt = end_dt.replace(tzinfo=datetime.timezone.utc)
        end_ts_int = int(end_dt.timestamp())
    except (ValueError, TypeError):
        return record

    best_ts = min(local_zones_index, key=lambda t: abs(t - end_ts_int), default=None)
    if best_ts is not None and abs(best_ts - end_ts_int) <= tolerance_sec:
        zones = local_zones_index[best_ts]
        if zones:
            return {**record, "zones": zones}
    return record


def _cloud_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a raw cloud /missionhistory record to the unified per-mission shape."""
    start_ts = record.get("startTime")
    end_ts   = record.get("timestamp")

    started_at = (
        datetime.datetime.fromtimestamp(int(start_ts), tz=datetime.timezone.utc).isoformat()
        if start_ts else None
    )
    ended_at = (
        datetime.datetime.fromtimestamp(int(end_ts), tz=datetime.timezone.utc).isoformat()
        if end_ts else None
    )

    duration_min = int(record.get("durationM") or record.get("doneM") or 0)
    run_min      = record.get("runM")
    pause_id     = record.get("pauseId")
    error_code   = int(pause_id) if pause_id and int(pause_id) > 0 else None

    return {
        "id":           f"c_{start_ts}" if start_ts else f"c_{end_ts}",
        "started_at":   started_at,
        "ended_at":     ended_at,
        "duration_min": duration_min,
        "run_min":      int(run_min) if run_min is not None else None,
        "area_sqft":    record.get("sqft"),
        "result":       record.get("classified_result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        [],   # F4a: populated by _inject_zones() below
        "error_code":   error_code,
        "recharges":    record.get("chrgs"),
        "evacuations":  record.get("evacs"),
        "dirt_events":  record.get("dirt"),
        "wifi_signal":  record.get("wlBars"),
        "source":       "cloud",
    }


def _local_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a local MissionStore record to the unified per-mission shape."""
    return {
        "id":           record.get("id", ""),
        "started_at":   record.get("started_at"),
        "ended_at":     record.get("ended_at"),
        "duration_min": record.get("duration_min"),
        "run_min":      None,
        "area_sqft":    record.get("area_sqft"),
        "result":       record.get("result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        record.get("zones", []),
        "error_code":   record.get("error_code"),
        "recharges":    None,
        "evacuations":  None,
        "dirt_events":  None,
        "wifi_signal":  None,
        "source":       "local",
    }


class MissionHistoryView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission_history"""

    url = "/api/roomba_plus/{entry_id}/mission_history"
    name = "api:roomba_plus:mission_history"
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        # F7o -- startup race guard: runtime_data may not be ready immediately
        # after HA start if a request arrives before setup completes.
        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data

        fmt = request.query.get("format", "summary").strip().lower()

        # F7o -- reject unknown format values with a clear 400
        if fmt not in _VALID_FORMATS:
            return self.json_message(
                f"Unknown format '{fmt}'. Valid values: {', '.join(sorted(_VALID_FORMATS))}",
                status_code=400,
            )

        # -- format=summary (default, backward compatible) --------------------
        if fmt == "summary":
            if data.mission_store is None:
                return self.json([], status_code=200)
            try:
                days = int(request.query.get("days", 28))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 28

            by_day = data.mission_store.query_by_day(days)
            result = [
                {
                    "date":      summary.date.isoformat(),
                    "total":     summary.total,
                    "completed": summary.completed,
                    "stuck":     summary.stuck,
                    "area_sqft": summary.area_sqft,
                    "result":    summary.result,
                }
                for summary in sorted(by_day.values(), key=lambda s: s.date)
            ]
            return self.json(result)

        # -- format=hazards ---------------------------------------------------
        # Stub: GridStore not yet implemented (v2.2.0).
        # Returns empty list so card developers can probe without 400.
        if fmt == "hazards":
            return self.json([])

        # -- format=records ---------------------------------------------------
        # F7o -- distinguish coordinator failure from genuinely empty data.
        if data.has_cloud and not data.cloud_coordinator.last_update_success:
            return self.json_message("Cloud coordinator unavailable", status_code=503)

        # Build local zone index for F4a injection into cloud records
        local_zones_index: dict[int, list[str]] = {}
        if data.mission_store is not None:
            local_zones_index = _build_local_zones_index(data.mission_store._records)

        if data.has_cloud and data.cloud_coordinator.raw_records:
            unified = [
                _cloud_record_to_unified(r)
                for r in data.cloud_coordinator.raw_records
            ]
            # F4a -- inject zone names from local store into cloud records
            if local_zones_index:
                unified = [_inject_zones(r, local_zones_index) for r in unified]
            # Cloud records are newest-first -- reverse to ascending for card
            records = list(reversed(unified))
        elif data.mission_store is not None:
            try:
                days = int(request.query.get("days", 90))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 90
            local = data.mission_store.query(days)
            records = [_local_record_to_unified(r) for r in local]
        else:
            records = []

        return self.json(records)
