"""REST API view for Roomba+ -- mission history endpoint.

GET /api/roomba_plus/{entry_id}/mission_history

Query parameters:
  days:   int  (1-90, default 28)   -- lookback window for day-summary format
  format: str  ("summary" | "records", default "summary")
            summary  -- day-aggregated DaySummary array (v0.1-beta card format,
                        always available, sourced from local MissionStore)
            records  -- per-mission array (v1.0 card format, sourced from cloud
                        raw_records when available, falls back to local
                        MissionStore records for robots without cloud credentials)

v2.1 changes:
  F4a -- zone names injected into cloud records (120 s timestamp tolerance)
  F7o -- startup race guard (503), coordinator failure (503), unknown format (400)

Registered once per HA instance (sentinel guard in __init__.py).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import datetime
import logging
from typing import TYPE_CHECKING, Any

from aiohttp import web
from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant
from homeassistant.util import dt as dt_util

from .const import DOMAIN, SQFT_TO_M2

if TYPE_CHECKING:
    from .models import RoombaData

_LOGGER = logging.getLogger(__name__)

# F7o -- valid format values; unknown values return 400
_VALID_FORMATS = {"summary", "records", "hazards", "export"}


def _build_local_zones_index(mission_store_records: list[dict]) -> dict[int, list[str]]:
    """Build a ts -> zone-names index from local MissionStore records.

    F4a -- used to inject zone names into cloud records which carry zones=[].
    Keys are integer Unix timestamps of ended_at. Tolerance matching is done
    at the call site (120 s window).
    """
    index: dict[int, list[str]] = {}
    for r in mission_store_records:
        ended_str = r.get("ended_at", "")
        zones = r.get("zones") or []
        if not ended_str or not zones:
            continue
        try:
            ended_dt = datetime.datetime.fromisoformat(ended_str)
        except (ValueError, TypeError):
            continue
        if ended_dt.tzinfo is None:
            ended_dt = ended_dt.replace(tzinfo=datetime.timezone.utc)
        index[int(ended_dt.timestamp())] = list(zones)
    return index


def _inject_zones(
    record: dict[str, Any],
    local_zones_index: dict[int, list[str]],
    tolerance_sec: int = 120,
) -> dict[str, Any]:
    """Return record with zones populated from local MissionStore when available.

    F4a -- matches on the cloud record's ended_at ISO string against the
    local ended_at index within tolerance_sec.  If a match is found and the
    local record has zone names, they replace the empty zones list.
    """
    end_ts_str = record.get("ended_at")
    if not end_ts_str or not local_zones_index:
        return record

    try:
        end_dt = datetime.datetime.fromisoformat(end_ts_str)
        if end_dt.tzinfo is None:
            end_dt = end_dt.replace(tzinfo=datetime.timezone.utc)
        end_ts_int = int(end_dt.timestamp())
    except (ValueError, TypeError):
        return record

    best_ts = min(local_zones_index, key=lambda t: abs(t - end_ts_int), default=None)
    if best_ts is not None and abs(best_ts - end_ts_int) <= tolerance_sec:
        zones = local_zones_index[best_ts]
        if zones:
            return {**record, "zones": zones}
    return record


def _cloud_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a raw cloud /missionhistory record to the unified per-mission shape."""
    start_ts = record.get("startTime")
    end_ts   = record.get("timestamp")

    started_at = (
        datetime.datetime.fromtimestamp(int(start_ts), tz=datetime.timezone.utc).isoformat()
        if start_ts else None
    )
    ended_at = (
        datetime.datetime.fromtimestamp(int(end_ts), tz=datetime.timezone.utc).isoformat()
        if end_ts else None
    )

    duration_min = int(record.get("durationM") or record.get("doneM") or 0)
    run_min      = record.get("runM")
    pause_id     = record.get("pauseId")
    error_code   = int(pause_id) if pause_id and int(pause_id) > 0 else None

    return {
        "id":           f"c_{start_ts}" if start_ts else f"c_{end_ts}",
        "started_at":   started_at,
        "ended_at":     ended_at,
        "duration_min": duration_min,
        "run_min":      int(run_min) if run_min is not None else None,
        "area_sqft":    record.get("sqft"),
        "result":       record.get("classified_result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        [],   # F4a: populated by _inject_zones() below
        "error_code":   error_code,
        "recharges":    record.get("chrgs"),
        "evacuations":  record.get("evacs"),
        "dirt_events":  record.get("dirt"),
        "wifi_signal":  record.get("wlBars"),
        "source":       "cloud",
        # v2.3.0 — from CR4 timeline merge; alignment_confidence injected in get()
        "room_coverage":        record.get("room_coverage"),
        "alignment_confidence": None,
    }


def _local_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a local MissionStore record to the unified per-mission shape.

    After v2.1.3 CR1/CR2: dirt_events, wifi_signal, and evacuations are
    populated when the record has been enriched by backfill_from_cloud() or
    merge_latest_from_cloud(). recharges stays None (no local accumulator).
    source remains "local" — reflects origin, not field provenance.
    """
    return {
        "id":           record.get("id", ""),
        "started_at":   record.get("started_at"),
        "ended_at":     record.get("ended_at"),
        "duration_min": record.get("duration_min"),
        "run_min":      None,                        # local source never has runM
        "area_sqft":    record.get("area_sqft"),
        "result":       record.get("result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        record.get("zones", []),
        "error_code":   record.get("error_code"),
        "recharges":    None,                        # no local accumulator
        "evacuations":  record.get("evacs"),         # from CR1 merge
        "dirt_events":  record.get("dirt"),          # from CR1 merge
        "wifi_signal":  record.get("wlBars"),        # from CR1 merge
        "source":       "local",
        # v2.3.0 — from CR4 timeline merge; alignment_confidence always null for local
        "room_coverage":        record.get("room_coverage"),
        "alignment_confidence": None,
    }


class MissionHistoryView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission_history"""

    url = "/api/roomba_plus/{entry_id}/mission_history"
    name = "api:roomba_plus:mission_history"
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        # F7o -- startup race guard: runtime_data may not be ready immediately
        # after HA start if a request arrives before setup completes.
        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data

        fmt = request.query.get("format", "summary").strip().lower()

        # F7o -- reject unknown format values with a clear 400
        if fmt not in _VALID_FORMATS:
            return self.json_message(
                f"Unknown format '{fmt}'. Valid values: {', '.join(sorted(_VALID_FORMATS))}",
                status_code=400,
            )

        # -- format=summary (default, backward compatible) --------------------
        if fmt == "summary":
            if data.mission_store is None:
                return self.json([], status_code=200)
            try:
                days = int(request.query.get("days", 28))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 28

            by_day = data.mission_store.query_by_day(days)
            # F12b — P4: per-day dirt density now cached on coordinator after each
            # cloud fetch; read directly instead of re-iterating records here.
            _p30d_baseline: float | None = None
            _daily_density: dict[str, float] = {}
            if data.has_cloud and data.cloud_coordinator is not None:
                _daily_density = data.cloud_coordinator.daily_dirt_density
                # 30-day baseline: median of all cached per-day medians
                all_densities = list(_daily_density.values())
                if len(all_densities) >= 5:
                    import statistics as _stat
                    _p30d_baseline = _stat.median(all_densities)

            # L5: per-room relative dirtiness from RobotProfileStore
            _room_dirt_relative: dict[str, float] | None = None
            _rps = getattr(data, "robot_profile_store", None)
            if _rps is not None:
                rd = _rps.room_dirt_relative()
                if rd:
                    _room_dirt_relative = rd

            result = [
                {
                    "date":               summary.date.isoformat(),
                    "total":              summary.total,
                    "completed":          summary.completed,
                    "stuck":              summary.stuck,
                    "area_sqft":          summary.area_sqft,
                    "result":             summary.result,
                    # F12b — dirt analytics read from coordinator cache
                    "dirt_density":       _daily_density.get(summary.date.isoformat()),
                    "relative_to_baseline": (
                        round(_daily_density[summary.date.isoformat()] / _p30d_baseline, 3)
                        if summary.date.isoformat() in _daily_density and _p30d_baseline
                        else None
                    ),
                    # L5 (v2.6.0) — per-room dirtiness index (once per day, not per-summary)
                    "room_dirt_index": _room_dirt_relative,
                }
                for summary in sorted(by_day.values(), key=lambda s: s.date)
            ]
            return self.json(result)

        # -- format=hazards ---------------------------------------------------
        # F9 — returns GridStore stuck hotspots and UMF-seeded obstacle zones.
        if fmt == "hazards":
            from .models import MapCapability
            if data.map_capability == MapCapability.NONE or data.grid_store is None:
                return self.json([])
            hazards = data.grid_store.hotspots()
            # Append UMF-seeded observed zones (source="robot_learned")
            if data.has_cloud:
                import math
                for centroid in data.cloud_coordinator.observed_zone_centroids:
                    x = centroid.get("x") or 0.0
                    y = centroid.get("y") or 0.0
                    hazards.append({
                        "gx":          None,
                        "gy":          None,
                        "x_mm":        x,
                        "y_mm":        y,
                        "stuck_count": None,
                        "room_name":   None,
                        "bearing_deg": int(math.degrees(math.atan2(x, y)) % 360),
                        "distance_mm": int(math.sqrt(x ** 2 + y ** 2)),
                        "source":      "robot_learned",
                    })
                # v2.3.0 Step 8 / Gap B — keepout zone centroids
                for zone in data.cloud_coordinator.keepout_zones:
                    cx = zone.get("cx") or zone.get("centroid_x") or zone.get("x")
                    cy = zone.get("cy") or zone.get("centroid_y") or zone.get("y")
                    if cx is not None and cy is not None:
                        cx, cy = float(cx), float(cy)
                        hazards.append({
                            "gx":          None,
                            "gy":          None,
                            "x_mm":        cx,
                            "y_mm":        cy,
                            "stuck_count": None,
                            "room_name":   None,
                            "bearing_deg": int(math.degrees(math.atan2(cx, cy)) % 360),
                            "distance_mm": int(math.sqrt(cx ** 2 + cy ** 2)),
                            "source":      "keepout",
                        })

            # v2.3.0 Step 8 — populate room_name via UmfAligner
            aligner = getattr(data, "umf_aligner", None)
            if aligner and aligner.aligned:
                for hazard in hazards:
                    source   = hazard.get("source")
                    x_mm     = hazard["x_mm"]
                    y_mm     = hazard["y_mm"]
                    if source == "stuck_events":
                        pt_umf = aligner.pose_to_umf(x_mm, y_mm)
                        if pt_umf:
                            hazard["room_name"] = aligner.room_name_at(*pt_umf)
                    elif source in ("robot_learned", "keepout"):
                        hazard["room_name"] = aligner.room_name_at(x_mm, y_mm)

            return self.json(hazards)

        # -- format=export (F15) ----------------------------------------------
        # Returns a versioned JSON bundle of all MissionStore records for
        # backup / migration purposes.  Schema is frozen at version 1;
        # new fields added in later versions carry null defaults.
        if fmt == "export":
            records_out: list[dict] = []
            if data.mission_store is not None:
                records_out = list(data.mission_store._records)
            blid = entry.data.get("blid", "")
            return self.json({
                "export_version": 1,
                "exported_at": dt_util.utcnow().isoformat(),
                "blid": blid,
                "record_count": len(records_out),
                "records": records_out,
            })

        # -- format=records ---------------------------------------------------
        # F7o -- distinguish coordinator failure from genuinely empty data.
        if data.has_cloud and not data.cloud_coordinator.last_update_success:
            return self.json_message("Cloud coordinator unavailable", status_code=503)

        # Build local zone index for F4a injection into cloud records
        local_zones_index: dict[int, list[str]] = {}
        if data.mission_store is not None:
            local_zones_index = _build_local_zones_index(data.mission_store._records)

        if data.has_cloud and data.cloud_coordinator.raw_records:
            unified = [
                _cloud_record_to_unified(r)
                for r in data.cloud_coordinator.raw_records
            ]
            # F4a -- inject zone names from local store into cloud records
            if local_zones_index:
                unified = [_inject_zones(r, local_zones_index) for r in unified]
            # Cloud records are newest-first -- reverse to ascending for card
            records = list(reversed(unified))
        elif data.mission_store is not None:
            try:
                days = int(request.query.get("days", 90))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 90
            local = data.mission_store.query(days)
            records = [_local_record_to_unified(r) for r in local]
        else:
            records = []

        # v2.3.0 — inject alignment_confidence for cloud-source records
        aligner = getattr(data, "umf_aligner", None)
        if aligner and aligner.aligned:
            conf = round(aligner.confidence, 2)
            for r in records:
                if r.get("source") == "cloud":
                    r["alignment_confidence"] = conf

        return self.json(records)


class MissionHistoryImportView(HomeAssistantView):
    """POST /api/roomba_plus/{entry_id}/mission_history/import

    F16 — import a v1 export bundle produced by format=export.
    Deduplicates against existing records by id — no overwrites.
    Returns {"imported": N, "skipped": N, "errors": []}.
    """

    url = "/api/roomba_plus/{entry_id}/mission_history/import"
    name = "api:roomba_plus:mission_history_import"
    requires_auth = True

    async def post(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data
        if data.mission_store is None:
            return self.json_message("Mission store unavailable", status_code=503)

        try:
            body = await request.json()
        except Exception:
            return self.json_message("Invalid JSON body", status_code=400)

        if not isinstance(body, dict):
            return self.json_message("Body must be a JSON object", status_code=400)

        version = body.get("export_version")
        if version is None:
            return self.json_message(
                "Missing export_version field", status_code=400
            )
        if version != 1:
            return self.json_message(
                f"Unsupported export_version {version!r}. Only version 1 is supported.",
                status_code=400,
            )

        incoming: list[dict] = body.get("records", [])
        if not isinstance(incoming, list):
            return self.json_message("records must be a list", status_code=400)

        # Bug 4 fix: reject oversized payloads before allocating memory.
        # 2 × MAX_RECORDS is a generous ceiling — legitimate exports from a
        # single robot can contain at most MAX_RECORDS (365) entries.
        from .mission_store import MAX_RECORDS
        if len(incoming) > MAX_RECORDS * 2:
            return self.json_message(
                f"records list too large: {len(incoming)} entries "
                f"(maximum {MAX_RECORDS * 2})",
                status_code=400,
            )

        # Build a full set of existing record IDs for O(1) dedup lookup
        existing_ids: set[str] = {
            r["id"] for r in data.mission_store._records if r.get("id")
        }

        imported = 0
        skipped = 0
        errors: list[str] = []

        for i, rec in enumerate(incoming):
            if not isinstance(rec, dict):
                errors.append(f"Record at index {i} is not a dict — skipped")
                skipped += 1
                continue
            rec_id = rec.get("id")
            if not rec_id:
                errors.append(f"Record at index {i} has no id field — skipped")
                skipped += 1
                continue
            if rec_id in existing_ids:
                skipped += 1
                continue
            # Append directly — bypasses MQTT dedup guard which only checks
            # the last 5 records; import needs full-set dedup (done above).
            data.mission_store._records.append(rec)
            existing_ids.add(rec_id)
            imported += 1

        if imported > 0:
            # Trim to MAX_RECORDS FIFO to maintain store invariant
            if len(data.mission_store._records) > MAX_RECORDS:
                data.mission_store._records = (
                    data.mission_store._records[-MAX_RECORDS:]
                )
            await data.mission_store.async_save(hass, entry_id)
            _LOGGER.info(
                "MissionHistoryImport: imported %d new record(s) for %s",
                imported, entry_id,
            )

        return self.json({
            "imported": imported,
            "skipped": skipped,
            "errors": errors,
        })


class HouseholdSummaryView(HomeAssistantView):
    """GET /api/roomba_plus/household?days=28

    F10b — aggregates all roomba_plus config entries. Returns per-robot
    breakdown with floor label, per-floor breakdown when labels are configured,
    and combined totals.
    """

    url = "/api/roomba_plus/household"
    name = "api:roomba_plus:household"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]

        try:
            days = int(request.query.get("days", 28))
            days = max(1, min(days, 90))
        except (ValueError, TypeError):
            days = 28

        entries = hass.config_entries.async_entries(DOMAIN)
        robots: list[dict] = []
        total_missions = 0
        total_completed = 0
        total_area: float | None = None
        floors: dict[str, dict] = {}

        for entry in entries:
            if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
                continue
            data = entry.runtime_data
            if data.mission_store is None:
                continue

            by_day = data.mission_store.query_by_day(days)
            missions   = sum(s.total     for s in by_day.values())
            completed  = sum(s.completed for s in by_day.values())
            area_vals  = [s.area_sqft   for s in by_day.values()
                          if s.area_sqft is not None]
            area: float | None = sum(area_vals) if area_vals else None
            comp_pct   = round(100 * completed / missions, 1) if missions else 0.0

            floor_label = getattr(data, "floor_label", "") or ""

            robots.append({
                "entry_id":       entry.entry_id,
                "name":           entry.title or "Roomba",
                "floor":          floor_label,
                "missions":       missions,
                "completed":      completed,
                "completion_pct": comp_pct,
                "area_sqft":      area,
            })
            total_missions  += missions
            total_completed += completed
            if area is not None:
                total_area = (total_area or 0.0) + area

            if floor_label:
                f = floors.setdefault(floor_label, {
                    "label": floor_label, "missions": 0,
                    "completed": 0, "area_sqft": None,
                })
                f["missions"]  += missions
                f["completed"] += completed
                if area is not None:
                    f["area_sqft"] = (f["area_sqft"] or 0.0) + area

        total_comp_pct = (
            round(100 * total_completed / total_missions, 1)
            if total_missions else 0.0
        )

        result: dict[str, Any] = {
            "period_days": days,
            "total": {
                "missions":       total_missions,
                "completed":      total_completed,
                "completion_pct": total_comp_pct,
                "area_sqft":      total_area,
            },
            "robots": robots,
        }
        if floors:
            result["floors"] = list(floors.values())

        return self.json(result)
