"""REST API view for Roomba+ — mission history endpoint.

GET /api/roomba_plus/{entry_id}/mission_history?days=28

Returns a JSON array of DaySummary records used by the Lovelace card
heatmap. Entity state cannot carry 28 days of history — this endpoint
is the only way to deliver it to the card.

Registered once per HA instance (sentinel guard in __init__.py).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from aiohttp import web
from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant

from .const import DOMAIN

if TYPE_CHECKING:
    from .models import RoombaData

_LOGGER = logging.getLogger(__name__)


class MissionHistoryView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission_history

    Query params:
      days: int (1–90, default 28) — lookback window

    Response: JSON array of DaySummary dicts sorted by date ascending.
    """

    url = "/api/roomba_plus/{entry_id}/mission_history"
    name = "api:roomba_plus:mission_history"
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        data: RoombaData = entry.runtime_data
        if data.mission_store is None:
            return self.json([], status_code=200)

        try:
            days = int(request.query.get("days", 28))
            days = max(1, min(days, 90))
        except (ValueError, TypeError):
            days = 28

        by_day = data.mission_store.query_by_day(days)
        result = [
            {
                "date": summary.date.isoformat(),
                "total": summary.total,
                "completed": summary.completed,
                "stuck": summary.stuck,
                "area_sqft": summary.area_sqft,
                "result": summary.result,
            }
            for summary in sorted(by_day.values(), key=lambda s: s.date)
        ]
        return self.json(result)
