"""MQTT callbacks for the Roomba+ integration.

Handles all push-based state updates from the robot:
  - Mission lifecycle detection (start → end phase transitions)
  - MissionStore record building and persistence
  - Map-retrain detection via user_pmapv_id changes
  - L3 runtime error state updates

Extracted from __init__.py (v2.0 refactor).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import datetime
import logging
from typing import TYPE_CHECKING, Any

from homeassistant.util import dt as dt_util

from .const import CONF_SMART_ZONE_DATA, END_SIGNAL_DEBOUNCE_COUNT, END_SIGNAL_MIN_HOLD_SECONDS, ROOM_TRANSITION_CANDIDATE_PHASES
import time as _time_mod

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry
    from .cloud_coordinator import IrobotCloudCoordinator
    from .models import RoombaConfigEntry, RoombaData

_LOGGER = logging.getLogger(__name__)

# v2.6.3 A+D — phases used ONLY for mission start/stuck detection (not end).
# Intentionally narrow: only phases where the robot is actively cleaning.
# hmPostMsn/hmUsrDock/stuck are NOT included — using had_cleaning_phase flag
# instead of last_phase guard eliminates the stuck-bypass bug (A) and the
# false mission-restart bug (D) without needing those phases in either set.
_ACTIVE_CLEANING_PHASES: frozenset[str] = frozenset({"run", "hmMidMsn", "evac"})

# Aligned with const.py MISSION_END_PHASES plus completed/cancelled which
# are valid end states in some firmware variants.
_MISSION_END_PHASES: frozenset[str] = frozenset(
    {"charge", "hmPostMsn", "stop", "completed", "cancelled"}
)

# v2.8.0 AUTO-ADVANCE-ROOM — phases that may represent an inter-room transition
# on lewis firmware (i7+/s9+) rather than a genuine mission end or recharge.
# Restricted to "charge" and "hmPostMsn": these are the two phases observed
# (per community report) appearing briefly between rooms. "stop", "completed",
# "cancelled" are excluded — those are unambiguous deliberate/terminal states
# and should never trigger an automatic room advance. "pause" and "stuck" are
# excluded by design (handled by the error/cycle guard below, but kept out of
# the candidate set entirely as a second layer of defence).
#
# v2.8.1 — moved to const.py as ROOM_TRANSITION_CANDIDATE_PHASES /
# END_SIGNAL_DEBOUNCE_COUNT so image.py's independent mission-end detection
# (map renderer / ZoneStore / GeometryStore / GridStore / OutlineStore) can
# share the exact same phase set and debounce threshold instead of risking a
# second, silently-diverging copy.
_ROOM_TRANSITION_CANDIDATE_PHASES = ROOM_TRANSITION_CANDIDATE_PHASES
_END_SIGNAL_DEBOUNCE_COUNT = END_SIGNAL_DEBOUNCE_COUNT
_END_SIGNAL_MIN_HOLD_SECONDS = END_SIGNAL_MIN_HOLD_SECONDS

# AUTO-ADVANCE-ROOM time-confidence threshold: time spent in the current room
# must be at least this fraction of the heuristic expected-per-room duration
# before a transient non-run phase is trusted as a genuine room completion.
# Conservative (0.5) since expected_room_sec is a uniform-split heuristic, not
# a true per-room estimate — large rooms legitimately take longer than average.
_ROOM_TRANSITION_MIN_ELAPSED_RATIO: float = 0.5


def _room_transition_confidence_ok(
    mission: dict[str, Any],
    mts: Any,
) -> bool:
    """AUTO-ADVANCE-ROOM (v2.8.0) confidence check.

    Combines four signals (per community feature request from Thonno) to
    decide whether a transient non-run cleanMissionStatus phase represents a
    genuine inter-room transition, as opposed to an error, a user pause, or a
    genuine low-battery recharge that happens to pass through the same phase
    string ("charge").

    Conditions (ALL must hold):
      1. No active error on the mission (mission.error == 0).
      2. cycle is still "clean" or "quick" — robot has not reported mission end.
      3. expected_room_sec is available AND time_in_current_room_sec is at
         least _ROOM_TRANSITION_MIN_ELAPSED_RATIO of the expected per-room
         duration.

    v2.8.0 (live wiring): the call site in this module now computes real
    per-room cloud TE1 time estimates via _compute_room_time_estimates() and
    passes them through set_mission_plan(room_estimates_sec=...), so
    expected_room_sec is populated whenever cloud data is available for the
    current room (falling back to a uniform total_estimated_sec / room_count
    split otherwise). AUTO-ADVANCE-ROOM is therefore live, not dormant, as
    long as at least a uniform estimate can be derived.

    Condition 2 shares the same cycle field as the INTER-ROOM-TRANSITION
    guard above and is subject to the same known reliability caveat — see
    the v2.8.1 END-DEBOUNCE comment on that guard. A cycle misread here would
    simply suppress an auto-advance (conservative failure mode) rather than
    corrupt state, so no debounce was added on this path.
    """
    error_code = mission.get("error", 0) or 0
    if error_code:
        return False

    cycle = mission.get("cycle", "")
    if cycle not in ("clean", "quick"):
        return False

    expected = mts.expected_room_sec
    if expected is None or expected <= 0:
        return False  # cannot confirm timing — conservative refusal (see docstring)

    elapsed = mts.time_in_current_room_sec
    return elapsed >= expected * _ROOM_TRANSITION_MIN_ELAPSED_RATIO


# ── Zone-name capture ─────────────────────────────────────────────────────────

def _capture_zone_names(
    entry: RoombaConfigEntry,
    reported: dict[str, Any],
) -> list[str]:
    """Resolve zone names at mission start for all robot types."""
    from .models import MapCapability

    data: RoombaData = entry.runtime_data
    if data.zone_store:                          # EPHEMERAL
        return [z.name for z in data.zone_store.zones if z.confirmed]
    if data.map_capability == MapCapability.SMART:
        last_cmd = reported.get("lastCommand", {})
        region_ids = [
            r.get("region_id")
            for r in (last_cmd.get("regions") or [])
            if r.get("region_id")
        ]
        if region_ids and data.cloud_coordinator:
            id_to_name = {
                r["id"]: r["name"]
                for r in data.cloud_coordinator.regions
                if r.get("id")
            }
            return [id_to_name[rid] for rid in region_ids if rid in id_to_name]
    return []  # NONE (600-series) or SMART without cloud


# ── Mission record builder ────────────────────────────────────────────────────

async def async_record_mission(
    hass: Any,
    entry: RoombaConfigEntry,
    mission: dict[str, Any],
    reported: dict[str, Any],
    zones: list[str],
    start_ts: int,
    nstuck_delta: int,
    recharge_min: int = 0,
    result_override: str | None = None,
) -> None:
    """Build and append a mission record to MissionStore.

    Args:
        hass:            HomeAssistant instance (for storage and dt_util).
        entry:           Config entry whose runtime_data holds the MissionStore.
        mission:         cleanMissionStatus dict from the end-of-mission MQTT message.
        reported:        Full reported state dict from the same MQTT message.
        zones:           Zone names captured at mission START (not end).
        start_ts:        mssnStrtTm cached at mission START. The 980/900-series
                         firmware resets this field to 0 in the end MQTT message,
                         so it must be captured when the cleaning phase begins.
        nstuck_delta:    bbrun.nStuck delta since mission start. Using the delta
                         rather than the lifetime counter prevents marking every
                         mission as stuck when bbrun arrives in the same packet.
        recharge_min:    F4e — minutes spent recharging mid-mission, accumulated
                         from rechrgM fields across hmMidMsn phase entries.
        result_override: F6c — when set, overrides the computed result string
                         (e.g. "blocked_timeout" from BlockingManager).
    """
    data: RoombaData = entry.runtime_data
    if data.mission_store is None:
        return

    now = dt_util.utcnow()

    if start_ts:
        started_at = datetime.datetime.fromtimestamp(
            start_ts, datetime.timezone.utc
        )
    else:
        # Fallback: wall-clock at recording time (duration will be ~0).
        # Should not be reached after the closure fix — log for diagnostics.
        started_at = now
        _LOGGER.warning(
            "MissionStore: no cached start_ts for mission — duration will be 0"
        )

    phase = mission.get("phase", "")
    error_code: int = mission.get("error", 0) or 0

    # F6c — result_override takes precedence (e.g. "blocked_timeout")
    if result_override:
        result = result_override
    elif error_code:
        result = "error"
    elif phase == "cancelled":
        result = "cancelled"
    elif nstuck_delta > 0:
        # F6h — default to stuck_and_abandoned; caller may override to
        # stuck_and_resumed if the phase returned to "run" after the stuck event.
        result = "stuck"
    else:
        result = "completed"

    elapsed_sec = (now - started_at).total_seconds()
    duration_min = max(0, round(elapsed_sec / 60))

    # Merge bbrun + runtimeStats — mirrors entity.py run_stats.
    # On i-series (lewis firmware) hr lives in runtimeStats, not bbrun.
    bbrun = reported.get("bbrun", {})
    runtime = reported.get("runtimeStats", {})
    bbrun_hr = bbrun.get("hr") or runtime.get("hr") or 0

    # F8b — capture error context at mission end
    # pose is None for firmware 3.20+ and 600-series; absent when null.
    error_position_mm: dict | None = None
    if error_code:
        pose_point = reported.get("pose", {}).get("point") if reported.get("pose") else None
        if pose_point:
            try:
                error_position_mm = {
                    "x": float(pose_point.get("x", 0)),
                    "y": float(pose_point.get("y", 0)),
                }
            except (TypeError, ValueError):
                pass

    phase_at_error: str | None = phase if error_code else None

    self_recovered: bool | None = (
        True  if result == "stuck_and_resumed"   else
        False if result == "stuck_and_abandoned" else
        None
    )

    record: dict[str, Any] = {
        "id": f"m_{int(started_at.timestamp())}",
        "started_at": started_at.isoformat(),
        "ended_at": now.isoformat(),
        "duration_min": duration_min,
        # v2.8.2: "or None" added — some robots (confirmed: 980 9-series with
        # aftermarket NiMH battery) report cleanMissionStatus.sqft as a literal
        # 0 rather than omitting the field, even for missions lasting hours.
        # Without this, the merge-precedence rule ("never overwrite a
        # non-None value") permanently locks out cloud backfill, even though
        # the cloud often has a real area value for the same mission. A
        # genuine 0-sqft mission is indistinguishable from "no data" anyway,
        # so this loses nothing and lets backfill work as intended.
        "area_sqft": mission.get("sqft") or None,   # None for 600-series — correct
        "result": result,
        "initiator": mission.get("initiator", "none"),
        "zones": zones,
        "error_code": error_code if error_code else None,
        "bbrun_hr": bbrun_hr,
        "recharge_min": recharge_min if recharge_min > 0 else None,  # F4e
        # F8b — error context fields (None when no error or no pose data)
        "error_position_mm": error_position_mm,
        "phase_at_error":    phase_at_error,
        "self_recovered":    self_recovered,
    }

    await data.mission_store.async_append(record)
    await data.mission_store.async_save(hass, entry.entry_id)

    # F6g — reset consecutive skip counter on any successful completion
    if result == "completed" and data.maintenance_store is not None:
        if data.maintenance_store.consecutive_skips > 0:
            data.maintenance_store.consecutive_skips = 0
            _LOGGER.debug("MissionStore: consecutive_skips reset on completed mission")
            await data.maintenance_store.async_save(hass, entry.entry_id)

    # F6e — check for mixed schedule patterns after each mission
    # Guard: only fire when hass is fully initialised (has config attribute)
    if getattr(hass, "is_running", False):
        from .repairs import async_check_mixed_schedule, async_check_mission_anomaly
        asyncio.run_coroutine_threadsafe(
            async_check_mixed_schedule(hass, entry), hass.loop
        )
        # L3 — check for consecutive anomalous missions after each append
        asyncio.run_coroutine_threadsafe(
            async_check_mission_anomaly(hass, entry), hass.loop
        )

    # Update L3 runtime error state.
    # Only update on error/stuck — do NOT clear on completed so the last
    # error remains visible until the next error occurs.
    if result in ("error", "stuck", "stuck_and_resumed", "stuck_and_abandoned"):
        data.last_error_code = error_code if error_code else None
        data.last_error_at   = now.isoformat()
        data.last_error_zone = zones[0] if zones else None

    _LOGGER.debug(
        "MissionStore: recorded %s result=%s duration=%dmin zones=%s",
        record["id"], result, duration_min, zones,
    )


# ── Callback factories ────────────────────────────────────────────────────────

def make_mission_callback(
    hass: Any,
    entry: RoombaConfigEntry,
) -> Any:
    """Return an MQTT message callback that tracks mission lifecycle.

    Returned callable is suitable for roomba.register_on_message_callback().
    Closure holds mutable state for phase tracking across messages.
    """
    last_phase: str = ""
    current_mission_zones: list[str] = []
    mission_start_ts: int = 0
    nstuck_at_start: int = 0
    # v2.8.1 (END-DEBOUNCE) — consecutive-message counter for the genuine-end
    # debounce below. Resets to 0 whenever a message does not look like a
    # genuine end (cycle still active, or phase back in an active phase).
    end_signal_streak: int = 0
    # v2.8.3 — monotonic timestamp of when the current end_signal_streak
    # first started (i.e. when streak went from 0 → 1 on an ambiguous phase).
    # Used together with END_SIGNAL_MIN_HOLD_SECONDS to reject rapid-burst
    # transitions: lewis firmware 22.52.10 sends exactly two consecutive
    # end-looking messages within ~21 ms during an inter-room transition —
    # the count-only gate (END_SIGNAL_DEBOUNCE_COUNT=2) fires on the burst.
    # The time gate ensures the signal must have been present for at least
    # 2 s, which a burst cannot satisfy but a genuinely-docked robot can.
    end_signal_first_ts: float = 0.0
    # F4e — accumulate recharge minutes across mid-mission recharge phases
    recharge_min_accumulator: int = 0
    last_recharge_phase_ts: float = 0.0
    # F6h — stuck recovery tracking
    had_stuck_event: bool = False
    stuck_cleared_ts: float = 0.0
    # v2.6.3 A+D — True once robot enters an active cleaning phase in this mission.
    # Replaces the last_phase-in-_CLEANING_PHASES guard so that:
    #   A) stuck → stop/charge correctly triggers mission end (not bypassed)
    #   D) stuck → run does NOT re-fire mission start (no false reset)
    had_cleaning_phase: bool = False

    def _on_mission_message(json_data: dict[str, Any]) -> None:
        nonlocal last_phase, current_mission_zones, mission_start_ts
        nonlocal nstuck_at_start, recharge_min_accumulator, last_recharge_phase_ts
        nonlocal had_stuck_event, stuck_cleared_ts, had_cleaning_phase
        nonlocal end_signal_streak, end_signal_first_ts

        reported = json_data.get("state", {}).get("reported", {})
        if "cleanMissionStatus" not in reported:
            return

        # v2.8.3 — MQTT-watchdog: stamp every message so RoombaMqttStale
        # binary sensor can detect silence during phase=run.
        entry.runtime_data.last_mqtt_message_ts = _time_mod.time()

        # v2.8.3 — FW-SENSOR: track softwareVer changes for binary_sensor.*_firmware_updated.
        # Only fires once per actual firmware upgrade (not on every message).
        _fw_ver = reported.get("softwareVer")
        if _fw_ver is not None:
            _data = entry.runtime_data
            if (
                _data.last_firmware_version is not None
                and _fw_ver != _data.last_firmware_version
            ):
                _data.firmware_updated_at = _time_mod.time()
                _LOGGER.info(
                    "Roomba+: firmware updated %s → %s",
                    _data.last_firmware_version, _fw_ver,
                )
            _data.last_firmware_version = _fw_ver
        if "cleanMissionStatus" not in reported:
            return
        mission = reported["cleanMissionStatus"]
        phase = mission.get("phase", "")

        # Capture zone names and start metadata at mission START.
        # lastCommand.regions is fresh at start — may be overwritten by end.
        # mssnStrtTm is cached here because 980/900-series firmware resets it
        # to 0 in the mission-end MQTT message.
        # v2.6.3 D — guard with had_cleaning_phase so stuck → run (recovery)
        # does NOT re-fire this block and corrupt mission_start_ts/nstuck_at_start.
        if phase in _ACTIVE_CLEANING_PHASES and not had_cleaning_phase:
            had_cleaning_phase = True
            current_mission_zones = _capture_zone_names(entry, reported)
            mission_start_ts = mission.get("mssnStrtTm") or 0
            bbrun = reported.get("bbrun", {})
            nstuck_at_start = bbrun.get("nStuck", 0)
            recharge_min_accumulator = 0
            last_recharge_phase_ts = 0.0
            had_stuck_event = False
            stuck_cleared_ts = 0.0
            _LOGGER.debug(
                "MissionStore: mission started ts=%s nstuck_baseline=%d",
                mission_start_ts, nstuck_at_start,
            )

            # F12a — record clean event in PresenceManager for window analytics.
            # record_clean_event() is idempotent and never raises.
            _pm = getattr(entry.runtime_data, "presence_manager", None)
            if _pm is not None:
                try:
                    _started_at = (
                        datetime.datetime.fromtimestamp(
                            mission_start_ts, tz=datetime.timezone.utc
                        )
                        if mission_start_ts
                        else datetime.datetime.now(datetime.timezone.utc)
                    )
                    _pm.record_clean_event(_started_at)
                except Exception:  # noqa: BLE001
                    pass

            # MS1 (v2.6.0): override initiator to "demand" when DirtThresholdManager
            # fired a start command within the last 30 seconds.
            _demand_ts = getattr(entry.runtime_data, "demand_triggered_ts", None)
            if isinstance(_demand_ts, float):
                import time as _t_mod
                if _t_mod.monotonic() - _demand_ts <= 30.0:
                    mission = dict(mission)  # copy to avoid mutating reported state
                    mission["initiator"] = "demand"
                    entry.runtime_data.demand_triggered_ts = None
                    _LOGGER.info("MissionStore: mission initiator overridden → demand")

        # F4e — accumulate recharge time on every hmMidMsn entry
        if phase == "hmMidMsn":
            rechrgM = reported.get("cleanMissionStatus", {}).get("rechrgM")
            if rechrgM is not None:
                # rechrgM is already cumulative for this charge leg
                recharge_min_accumulator += int(rechrgM)
            elif last_recharge_phase_ts == 0.0:
                # Fallback: record timestamp to compute elapsed on phase exit
                last_recharge_phase_ts = _time_mod.monotonic()

        # F4e fallback: if rechrgM was unavailable, compute elapsed time
        if last_phase == "hmMidMsn" and phase != "hmMidMsn" and last_recharge_phase_ts > 0.0:
            elapsed_min = int((_time_mod.monotonic() - last_recharge_phase_ts) / 60)
            recharge_min_accumulator += elapsed_min
            last_recharge_phase_ts = 0.0

        # F6h — detect stuck event: nStuck increased during this mission.
        # v2.6.3 A — check whenever mission is active (had_cleaning_phase=True),
        # not just during specific phases. This catches nStuck increments that
        # arrive while the robot is in the 'stuck' phase itself.
        if had_cleaning_phase and "bbrun" in reported and not had_stuck_event:
            bbrun_now = reported["bbrun"]
            current_nstuck = bbrun_now.get("nStuck", nstuck_at_start)
            if current_nstuck > nstuck_at_start:
                had_stuck_event = True
                stuck_cleared_ts = _time_mod.monotonic()
                _LOGGER.debug("MissionStore: stuck event detected during mission")

        # F6h — if robot returned to cleaning after a stuck event, mark resumed
        if had_stuck_event and phase in _ACTIVE_CLEANING_PHASES and last_phase not in _ACTIVE_CLEANING_PHASES:
            # Robot re-entered active cleaning after a non-active phase (e.g. stuck)
            if stuck_cleared_ts > 0 and (_time_mod.monotonic() - stuck_cleared_ts) < 1800:
                # Still within 30-min window — mark as resumed
                stuck_cleared_ts = _time_mod.monotonic()  # reset timer for next end

        # v2.6.3 A — use had_cleaning_phase instead of last_phase guard so that
        # stuck → stop/charge (stuck_and_abandoned) is correctly detected.
        #
        # v2.8.0 INTER-ROOM-TRANSITION guard: on lewis firmware (i7+/s9+),
        # the robot briefly shows mission-end phases (charge, hmPostMsn) between
        # rooms in a multi-room mission.  Each room segment ends with a non-run
        # phase before the next room begins.
        #
        # Primary discriminator: cleanMissionStatus.cycle
        #   "clean" / "quick" → robot is still in an active mission (inter-room)
        #   "none"  / absent  → robot truly finished, heading to dock
        #
        # Without this guard, _mts.clear() fires at every room transition,
        # resetting run_sec=0, mission_id=None → progress resets to 0% each room.
        # (Thonno regression reported for v2.7.6.)
        #
        # v2.8.1 (END-DEBOUNCE): cycle alone was confirmed insufficient — Thonno
        # reproduced a reset even with the v2.8.0 guard above. The symptom
        # (elapsed time reset to 0, then current_room/next_room briefly showing
        # raw region IDs and progress/estimated-remaining going Unknown) is
        # consistent with cycle momentarily reporting outside ("clean","quick")
        # on a single inter-room MQTT message while the mission is genuinely
        # still running.
        #
        # An earlier draft of this fix tried corroborating with nMssn (the
        # lifetime mission counter), but nMssn is constant for the entire
        # duration of one mission — start through true end — so "nMssn
        # changed" can never confirm a genuine end of *this* mission; it only
        # ever becomes true once a *later* mission starts. That approach was
        # caught and dropped by the existing test_mission_timer_store.py
        # genuine-end tests before shipping.
        #
        # Fix actually used: debounce, scoped to the genuinely ambiguous
        # phases only. _ROOM_TRANSITION_CANDIDATE_PHASES ("charge",
        # "hmPostMsn") are the two phases already established (by
        # AUTO-ADVANCE-ROOM, above) as appearing both at genuine mission end
        # AND transiently between rooms — exactly where a cycle misread can
        # cause a false end. "stop", "completed", "cancelled" are deliberate,
        # unambiguous terminal phases that are never used for inter-room
        # signalling, so they keep confirming on a single message, same as
        # before.  A genuine end on an ambiguous phase is a stable state —
        # the robot keeps reporting it on every subsequent message while
        # sitting docked — while a transient inter-room blip is not: the
        # very next message reverts to phase=="run" or a correctly-reported
        # cycle. Requiring the signal to hold for _END_SIGNAL_DEBOUNCE_COUNT
        # consecutive messages filters out single-message blips at the cost
        # of a small, acceptable detection delay on genuine ends.
        _cycle = mission.get("cycle", "")
        _is_inter_room_transition = _cycle in ("clean", "quick")
        _looks_like_end = phase in _MISSION_END_PHASES and not _is_inter_room_transition
        _ambiguous_end_phase = phase in _ROOM_TRANSITION_CANDIDATE_PHASES

        if had_cleaning_phase:
            if not _looks_like_end:
                end_signal_streak = 0
                end_signal_first_ts = 0.0
            elif _ambiguous_end_phase:
                if end_signal_streak == 0:
                    # Record when the current streak started — used by the
                    # v2.8.3 time gate to reject rapid inter-room bursts.
                    end_signal_first_ts = _time_mod.monotonic()
                end_signal_streak += 1
            else:
                # Unambiguous terminal phase — confirm immediately.
                end_signal_streak = _END_SIGNAL_DEBOUNCE_COUNT

        if phase in _MISSION_END_PHASES and had_cleaning_phase:
            _time_held = (
                _time_mod.monotonic() - end_signal_first_ts
                if end_signal_first_ts > 0
                else 0.0
            )
            _LOGGER.debug(
                "MissionStore: end-phase check phase=%s cycle=%s ambiguous=%s "
                "is_inter_room=%s end_signal_streak=%d time_held=%.3fs",
                phase, _cycle, _ambiguous_end_phase,
                _is_inter_room_transition, end_signal_streak, _time_held,
            )
            if (
                _ambiguous_end_phase
                and end_signal_streak >= _END_SIGNAL_DEBOUNCE_COUNT
                and _time_held < _END_SIGNAL_MIN_HOLD_SECONDS
            ):
                _LOGGER.info(
                    "MissionStore: end-phase burst rejected "
                    "(time_held=%.3fs < %.1fs) — mission still active",
                    _time_held, _END_SIGNAL_MIN_HOLD_SECONDS,
                )

        if (
            phase in _MISSION_END_PHASES
            and had_cleaning_phase
            and _looks_like_end
            and end_signal_streak >= _END_SIGNAL_DEBOUNCE_COUNT
            and (
                not _ambiguous_end_phase
                or (
                    _time_mod.monotonic() - end_signal_first_ts
                    >= _END_SIGNAL_MIN_HOLD_SECONDS
                )
            )
        ):
            had_cleaning_phase = False
            end_signal_streak = 0
            end_signal_first_ts = 0.0
            bbrun_end = reported.get("bbrun", {})
            nstuck_delta = max(0, bbrun_end.get("nStuck", 0) - nstuck_at_start)

            # F6h — classify stuck recovery outcome
            result_override: str | None = None
            if had_stuck_event and nstuck_delta > 0:
                # stuck_and_resumed: robot had stuck event but kept cleaning
                # (stuck_cleared_ts was reset when it re-entered run phase)
                # We distinguish by whether total run time is > 5 min post-stuck,
                # using mission duration as a proxy. If mission was short (<10 min)
                # and we have nstuck, it abandoned immediately.
                elapsed_total = (
                    _time_mod.monotonic() - (stuck_cleared_ts if stuck_cleared_ts else 0)
                )
                # A mission that lasted >5 min after the stuck event = resumed
                if stuck_cleared_ts > 0 and elapsed_total > 300:
                    result_override = "stuck_and_resumed"
                else:
                    result_override = "stuck_and_abandoned"

            asyncio.run_coroutine_threadsafe(
                async_record_mission(
                    hass,
                    entry,
                    mission,
                    reported,
                    list(current_mission_zones),
                    start_ts=mission_start_ts,
                    nstuck_delta=nstuck_delta,
                    recharge_min=recharge_min_accumulator,  # F4e
                    result_override=result_override,         # F6h
                ),
                hass.loop,
            )
            # MP1 (v2.6.0): clear mission timer at end
            _mts = getattr(entry.runtime_data, "mission_timer_store", None)
            if _mts is not None:
                _mts.clear(hass, entry.entry_id)

            current_mission_zones = []
            mission_start_ts = 0
            nstuck_at_start = 0
            recharge_min_accumulator = 0
            last_recharge_phase_ts = 0.0
            had_stuck_event = False
            stuck_cleared_ts = 0.0
            # had_cleaning_phase already reset to False above

        # MP1 (v2.6.0): accumulate run-only seconds in MissionTimerStore
        _mts_upd = getattr(entry.runtime_data, "mission_timer_store", None)
        if _mts_upd is not None and mission_start_ts:
            _mission_id = f"{entry.data.get('blid', '')}_{mission_start_ts}"
            if phase == "run":
                _is_new_mission = _mts_upd.mission_id != _mission_id
                _mts_upd.on_phase_run(_mission_id, hass, entry.entry_id)
                if _is_new_mission:
                    # v2.7.5: wire set_mission_plan on mission start so
                    # planned_rooms is populated for current_room fallback
                    # and for MTS persistence across HA restarts.
                    _master = (
                        getattr(entry.runtime_data.roomba, "master_state", None) or {}
                    )
                    _rep = (_master.get("state") or {}).get("reported") or {}
                    _regions = (_rep.get("lastCommand") or {}).get("regions") or []
                    _zone = entry.options.get(CONF_SMART_ZONE_DATA, {})
                    _names = [
                        r.get("region_name")
                        or (_zone.get(str(r.get("region_id", ""))) or {}).get("name")
                        or str(r.get("region_id", ""))
                        for r in _regions
                        if isinstance(r, dict)
                        and (r.get("region_name") or r.get("region_id"))
                    ]
                    if _names:
                        # v2.8.0 AUTO-ADVANCE-ROOM (live wiring): use the real
                        # cloud TE1 per-room time estimates instead of the
                        # previous hardcoded 0. total_estimated_sec is the sum
                        # of available per-room estimates (None entries are
                        # excluded from the sum, not treated as 0 seconds).
                        # Deferred import: sensor.py imports from this package's
                        # __init__.py (roomba_reported_state), and __init__.py
                        # imports this module at load time — a top-level import
                        # here would be circular. Safe at call time since both
                        # modules are fully loaded by then.
                        #
                        # Bug-hunt: this entire block is wrapped because
                        # _compute_room_time_estimates() reads cloud_coordinator
                        # and roomba_reported_state() — an unexpected None or a
                        # malformed cloud payload there must not crash this
                        # whole MQTT callback (which would also break mission
                        # tracking, stuck detection, etc. for this message).
                        # Falls back to the pre-v2.8.0 behaviour (no estimate)
                        # on any failure, same as if cloud data were absent.
                        _room_secs: list[float | None] = [None] * len(_names)
                        _total_est: float | None = None
                        try:
                            from .sensor import _compute_room_time_estimates
                            _room_secs = _compute_room_time_estimates(entry, _names)
                            _known_secs: list[float] = []
                            for _s in _room_secs:
                                if _s is None:
                                    continue
                                try:
                                    _sf = float(_s)
                                except (TypeError, ValueError):
                                    continue
                                if _sf > 0:
                                    _known_secs.append(_sf)
                            _total_est = sum(_known_secs) if _known_secs else None
                        except Exception:  # noqa: BLE001
                            _LOGGER.debug(
                                "AUTO-ADVANCE-ROOM: room time estimate lookup "
                                "failed — continuing without estimates",
                                exc_info=True,
                            )
                        _mts_upd.set_mission_plan(
                            _mission_id,
                            _names,
                            _total_est,
                            hass,
                            entry.entry_id,
                            room_estimates_sec=_room_secs,
                        )
            else:
                # v2.7.5: pass hass/entry_id so on_phase_other can save
                # the flushed delta without waiting for next on_phase_run.
                _mts_upd.on_phase_other(hass, entry.entry_id)

                # v2.8.0 AUTO-ADVANCE-ROOM — automatic confidence-based room
                # advancement, per community feature request (Thonno).
                # Edge-triggered (last_phase != phase) so a phase that stays
                # e.g. "charge" across multiple consecutive MQTT messages only
                # attempts the advance once — prevents repeatedly advancing
                # current_room_idx during a single genuine recharge dwell.
                if (
                    last_phase != phase
                    and phase in _ROOM_TRANSITION_CANDIDATE_PHASES
                    and _room_transition_confidence_ok(mission, _mts_upd)
                ):
                    _advanced = _mts_upd.advance_room(hass, entry.entry_id)
                    if _advanced:
                        _LOGGER.info(
                            "AUTO-ADVANCE-ROOM: advanced to room %d/%d (%s) "
                            "on phase=%s confidence signal",
                            _mts_upd.current_room_idx + 1,
                            len(_mts_upd.planned_rooms),
                            _mts_upd.current_room,
                            phase,
                        )

        last_phase = phase

    return _on_mission_message


def make_mission_complete_callback(
    hass: Any,
    cloud_coordinator: IrobotCloudCoordinator,
) -> Any:
    """Return an MQTT callback that triggers a cloud refresh at mission end.

    F4b — fires async_request_refresh() when a mission-end phase transition
    is detected, eliminating the up-to-24h staleness in cloud sensors after
    a mission completes.  Parallel pattern to make_map_retrain_callback().

    v2.6.3 A — uses had_cleaning_phase flag instead of last_phase guard so
    stuck → stop/charge (stuck_and_abandoned missions) also trigger a refresh.
    """
    last_phase: str = ""
    had_cleaning_phase: bool = False

    def _on_roomba_message(json_data: dict[str, Any]) -> None:
        nonlocal last_phase, had_cleaning_phase
        reported = json_data.get("state", {}).get("reported", {})
        if "cleanMissionStatus" not in reported:
            return
        mission = reported["cleanMissionStatus"]
        phase = mission.get("phase", "")
        if phase in _ACTIVE_CLEANING_PHASES:
            had_cleaning_phase = True
        else:
            # v2.8.0 INTER-ROOM-TRANSITION guard (same discriminator as
            # _on_mission_message): lewis firmware briefly shows a
            # mission-end-looking phase (charge/hmPostMsn) between rooms
            # during a multi-room mission. Without this guard, this callback
            # fired a cloud async_request_refresh() at every room transition
            # instead of only at genuine mission end — wasted cloud API
            # calls and rate-limit risk on multi-room lewis-firmware missions.
            _cycle = mission.get("cycle", "")
            _is_inter_room_transition = _cycle in ("clean", "quick")
            if (
                phase in _MISSION_END_PHASES
                and had_cleaning_phase
                and not _is_inter_room_transition
            ):
                had_cleaning_phase = False
                _LOGGER.debug(
                    "Roomba+ cloud: mission ended (phase %s → %s) — requesting refresh",
                    last_phase, phase,
                )
                asyncio.run_coroutine_threadsafe(
                    cloud_coordinator.async_request_refresh(), hass.loop
                )
        last_phase = phase

    return _on_roomba_message


def make_map_retrain_callback(
    hass: Any,
    cloud_coordinator: IrobotCloudCoordinator,
) -> Any:
    """Return an MQTT message callback that detects Smart Map retrains.

    Triggers an immediate cloud coordinator refresh when user_pmapv_id
    changes in the MQTT state — earlier than the 24-hour poll interval.
    """
    last_pmapv: dict[str, str] = {}  # pmap_id → last seen pmapv_id

    def _on_roomba_message(json_data: dict[str, Any]) -> None:
        reported = json_data.get("state", {}).get("reported", {})
        pmaps: list[dict] = reported.get("pmaps", [])
        changed = False
        for pmap_entry in pmaps:
            for pid, pmapv in pmap_entry.items():
                if last_pmapv.get(pid) not in (None, pmapv):
                    _LOGGER.info(
                        "Roomba+ cloud: user_pmapv_id changed for pmap %s "
                        "(%s → %s) — triggering cloud refresh",
                        pid[:12], last_pmapv[pid][:12], pmapv[:12],
                    )
                    changed = True
                last_pmapv[pid] = pmapv
        if changed:
            asyncio.run_coroutine_threadsafe(
                cloud_coordinator.async_request_refresh(), hass.loop
            )

    return _on_roomba_message
