"""Cloud data coordinator for Roomba+.

Polls the iRobot cloud API once per HA session (at setup) and again whenever
a map retrain is detected via MQTT (user_pmapv_id change). Between those
events the cloud data is stable — pmaps only change when the user physically
retrains or edits room boundaries.

The coordinator is only created for MapCapability.SMART robots AND when the
user has supplied iRobot cloud credentials. All existing local-MQTT behaviour
is completely unaffected when this coordinator is absent.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from datetime import timedelta
from typing import TYPE_CHECKING, Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .cloud_api import AuthenticationError, CloudApiError, IrobotCloudApi

if TYPE_CHECKING:
    from .mission_store import MissionStore

_LOGGER = logging.getLogger(__name__)

# Cloud map data changes only on map retrain — poll once per day as a
# backstop; real refresh is triggered by user_pmapv_id MQTT change.
_CLOUD_POLL_INTERVAL = timedelta(hours=24)



def classify_mission_result(record: dict) -> str:
    """Classify a raw /missionhistory record into a canonical result string.

    Uses the v2.0 classification scheme, which is more granular than the
    v1.9 MQTT-based scheme in callbacks.py:

      "completed"          — done="done"
      "cancelled_by_user"  — done_raw="usrEnd" (user pressed stop in the app)
      "cancelled"          — done="cncl" but not user-initiated
      "error_{code}"       — done="stuck" + pauseId>0, e.g. "error_17"
      "stuck"              — done="stuck" + pauseId=0 (no specific code)
      "unknown"            — unrecognised done value, logged for analysis

    Priority: done_raw wins over done for user-cancellation detection because
    the iRobot cloud normalises "usrEnd" → "cncl" in the done field, losing
    the user-intent signal. pauseId is the authoritative error code from the
    cloud — more reliable than cleanMissionStatus.error from MQTT, which
    sometimes never arrives on 900-series firmware.

    Args:
        record: A single raw record dict from /missionhistory.

    Returns:
        Canonical result string for use in sensors and REST API.
    """
    done: str = record.get("done", "") or ""
    done_raw: str = record.get("done_raw", "") or ""
    pause_id: int = int(record.get("pauseId", 0) or 0)

    if done == "done":
        return "completed"

    if done_raw == "usrEnd":
        return "cancelled_by_user"

    if done in ("cncl",):
        return "cancelled"

    if done == "stuck":
        if pause_id > 0:
            return f"error_{pause_id}"
        return "stuck"

    # Known done values confirmed from field logs (June 2026, Roomba 980 v2.4.17):
    if done == "ok":
        # Cloud normalisation of a successful mission (alternate to "done")
        return "completed"

    if done == "full":
        # Robot stopped because the bin is full
        return "cancelled"

    if done == "bat":
        # Robot stopped due to battery depletion (failed to reach dock)
        return "error_battery"

    if done == "schErr":
        # Schedule error — robot failed to start at scheduled time.
        # pauseId 215 = schedule conflict, 216 = schedule internal error.
        if pause_id > 0:
            return f"error_{pause_id}"
        return "cancelled"

    if done == "inc":
        # Mission incomplete — robot aborted before finishing.
        # pauseId carries the error code when present (confirmed: pauseId=48
        # from CR3 debug, June 2026 — error during room navigation start).
        if pause_id > 0:
            return f"error_{pause_id}"
        return "cancelled"

    if done:
        import logging
        logging.getLogger(__name__).debug(
            "classify_mission_result: unknown done=%r done_raw=%r pauseId=%d — "
            "logging for further analysis",
            done, done_raw, pause_id,
        )
    return "unknown"


def _normalize_mission_history(raw: dict) -> dict:
    """Normalize a raw /missionhistory record into a consistent shape.

    The iRobot cloud /missionhistory endpoint (confirmed from field logs) returns
    a list of individual mission records. Each record uses iRobot-internal field
    names that differ from the local MQTT state:

      durationM  — mission duration in minutes (cleaning + recharge time)
      done       — True if mission completed successfully
      chrgs      — number of mid-mission recharges
      chrgM      — minutes spent recharging during this mission
      dirt       — dirt detection events (scrub count)
      sqft       — area cleaned this mission in sq ft (may be present)

    This function is called with the FIRST record from the list. For aggregate
    lifetime stats, the coordinator passes the full list to _aggregate_history()
    and stores those results instead.

    This single-record normalizer is kept for backward compatibility and for
    cases where the API may return a summary dict rather than a list.

    Canonical output shape:
      {
        "runtimeStats": {"sqft": int, "hr": int, "min": int},
        "bbmssn":       {"nMssn": int},
      }
    """
    if not raw:
        return {}

    runtime = raw.get("runtimeStats") or {}
    bbrun   = raw.get("bbrun") or {}
    bbmssn  = raw.get("bbmssn") or {}

    # Try legacy/accumulator paths first (some account types return summary dict)
    sqft = runtime.get("sqft") or bbrun.get("sqft")
    hr   = runtime.get("hr")   or bbrun.get("hr")
    mn   = runtime.get("min")  or bbrun.get("min")
    n_mssn = bbmssn.get("nMssn") or raw.get("nMssn")

    # iRobot individual-record format: durationM in minutes
    if hr is None and mn is None:
        duration_m = raw.get("durationM") or raw.get("doneM") or 0
        if duration_m:
            hr = int(duration_m) // 60
            mn = int(duration_m) % 60

    # sqft from individual record — only if no better source found
    # NOTE: raw["sqft"] in individual records = THIS MISSION only, not lifetime.
    # We deliberately do NOT use it here to avoid showing per-mission sqft as
    # lifetime total. The aggregate path handles lifetime correctly.
    if sqft is None:
        sqft = raw.get("sqft")  # per-mission fallback, marked in attributes

    result: dict = {}
    if sqft is not None or hr is not None or mn is not None:
        result["runtimeStats"] = {}
        if sqft is not None:
            result["runtimeStats"]["sqft"] = int(sqft)
        if hr is not None:
            result["runtimeStats"]["hr"] = int(hr)
        if mn is not None:
            result["runtimeStats"]["min"] = int(mn)
    if n_mssn is not None:
        result["bbmssn"] = {"nMssn": int(n_mssn)}

    return result


def _aggregate_history(records: list) -> dict:
    """Aggregate a list of individual mission records into totals.

    Confirmed field names from field logs (980 firmware v2.4.17-138):
      nMssn     — LIFETIME mission count (same value in every record)
      durationM — this mission duration in minutes (run + recharge time)
      runM      — actual cleaning time in minutes (excl. recharge)
      chrgM     — time spent recharging mid-mission in minutes
      chrgs     — number of mid-mission recharges
      done      — mission result string: "done" / "stuck" / other
      pauseId   — error code when done != "done" (17 = cannot find home)
      sqft      — area cleaned this mission in sq ft
      evacs     — bin evacuation count this mission
      initiator — who started the mission

    nMssn strategy: every record contains the LIFETIME mission counter at
    the time of that mission. We read it from the first record to get the
    most recent lifetime total, NOT len(records) which is just the API
    window size (~30 days).

    For running time and area we SUM across all records — these represent
    the total for the API window (not lifetime).
    """
    if not records:
        return {}

    total_min  = 0
    total_sqft = 0
    has_sqft   = False

    # nMssn is the lifetime counter embedded in each record.
    # Use the first valid record's value for the current lifetime total.
    n_mssn_lifetime = None
    for r in records:
        if isinstance(r, dict) and r.get("nMssn") is not None:
            n_mssn_lifetime = int(r["nMssn"])
            break

    # Fall back to record count if nMssn not found (older firmware)
    n_mssn = n_mssn_lifetime if n_mssn_lifetime is not None else len(records)

    for r in records:
        if not isinstance(r, dict):
            continue
        # Use runM (actual cleaning time) preferred over durationM (incl. recharge)
        # Fall back chain: runM -> durationM -> doneM
        duration_m = r.get("runM") or r.get("durationM") or r.get("doneM") or 0
        total_min += int(duration_m)
        sqft = r.get("sqft")
        if sqft is not None:
            total_sqft += int(sqft)
            has_sqft = True

    result: dict = {
        "bbmssn": {"nMssn": n_mssn},
    }
    if total_min > 0:
        result["runtimeStats"] = {
            "hr":  total_min // 60,
            "min": total_min % 60,
        }
        if has_sqft:
            result["runtimeStats"]["sqft"] = total_sqft

    return result


class IrobotCloudCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Coordinator for iRobot cloud data (pmaps, mission history, favorites).

    data structure after a successful update:
    {
        "pmaps": [...],          # list of pmap dicts from /pmaps
        "mission_history": {...},# from /missionhistory
        "favorites": [...],      # from /user/favorites
    }
    All keys are always present; they default to empty list/dict on error.

    For EPHEMERAL robots (980/900-series): pmaps and favorites are always
    empty lists — only missionhistory is fetched. For SMART robots all
    three endpoints are fetched.
    """

    def __init__(
        self,
        hass: HomeAssistant,
        config_entry: ConfigEntry,
        blid: str,
        username: str,
        password: str,
        has_pmaps: bool = False,
        mission_store: "MissionStore | None" = None,
    ) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"iRobot cloud ({blid})",
            config_entry=config_entry,
            update_interval=_CLOUD_POLL_INTERVAL,
        )
        self.blid = blid
        self._has_pmaps = has_pmaps
        self._mission_store = mission_store   # CR3 — fallback source
        country_code = (hass.config.country or "US").upper()
        self.api = IrobotCloudApi(
            username=username,
            password=password,
            session=async_get_clientsession(hass),
            country_code=country_code,
        )
        _LOGGER.debug(
            "iRobot cloud: using country_code=%s, has_pmaps=%s for %s",
            country_code, has_pmaps, blid,
        )

    async def _async_setup(self) -> None:
        """Authenticate once when the coordinator is first started."""
        try:
            await self.api.authenticate()
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud credentials are invalid: {exc}"
            ) from exc
        except CloudApiError as exc:
            # Transient — let HA retry via ConfigEntryNotReady pathway
            raise UpdateFailed(f"iRobot cloud setup failed: {exc}") from exc

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch current cloud data for this robot."""
        result: dict[str, Any] = {
            "pmaps": [],
            "mission_history": {},
            "mission_history_raw": [],   # v2.0: full per-mission record list
            "favorites": [],
            "automations": {},           # v2.1 F7l: iRobot Genius rules (shape TBD)
            "umf": {},                   # v2.2 F9: UMF floor plan data (SMART robots)
        }
        try:
            async with asyncio.timeout(30):
                # pmaps and favorites require cap.pmaps — SMART robots only.
                # missionhistory is account-level and available for all robots.
                if self._has_pmaps:
                    result["pmaps"] = await self.api.get_pmaps(self.blid)
                    result["favorites"] = await self.api.get_favorites()
                raw_history = await self.api.get_mission_history(self.blid)
                # F7l — fetch automations endpoint; fails gracefully
                try:
                    result["automations"] = await self.api.get_automations()
                except Exception:  # noqa: BLE001
                    _LOGGER.debug(
                        "iRobot cloud: automations endpoint unavailable for %s "
                        "(endpoint may not exist for this account type)",
                        self.blid,
                    )
                    result["automations"] = {}
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud authentication failed: {exc}"
            ) from exc
        except CloudApiError as exc:
            raise UpdateFailed(f"iRobot cloud update failed: {exc}") from exc

        # The /missionhistory endpoint returns a list of records.
        # Structure varies by firmware/region:
        #   - Some accounts: list where [0] is a lifetime accumulator dict
        #     with runtimeStats.sqft/hr/min and bbmssn.nMssn
        #   - Some accounts: list of individual mission records where lifetime
        #     totals are in bbrun.sqft/hr and bbmssn.nMssn
        #   - Some firmware: a single dict directly
        # We log the raw structure at DEBUG level so users can report issues.
        if isinstance(raw_history, list) and raw_history:
            _first  = raw_history[0] if isinstance(raw_history[0], dict) else {}
            _second = (
                raw_history[1] if len(raw_history) > 1 and isinstance(raw_history[1], dict)
                else {}
            )

            # field_coverage: count of records containing each key.
            # array_stats: min/max element count + first-element shape per array key.
            # nested_keys: sub-keys one level deep for dict-valued fields.
            _all_keys: set[str] = set()
            _field_coverage: dict[str, int] = {}
            _array_stats: dict[str, dict] = {}
            _nested_keys: dict[str, set] = {}

            for _r in raw_history:
                if not isinstance(_r, dict):
                    continue
                _all_keys.update(_r.keys())
                for _k, _v in _r.items():
                    _field_coverage[_k] = _field_coverage.get(_k, 0) + 1
                    if isinstance(_v, list) and _v:
                        _s = _array_stats.setdefault(_k, {"min": len(_v), "max": 0})
                        _s["min"] = min(_s["min"], len(_v))
                        _s["max"] = max(_s["max"], len(_v))
                        if "first_element" not in _s:
                            _s["first_element"] = _v[0]
                    elif isinstance(_v, dict) and _v:
                        _nested_keys.setdefault(_k, set()).update(_v.keys())

            _n = len([_r for _r in raw_history if isinstance(_r, dict)])
            _coverage_summary = {
                _k: f"{_field_coverage[_k]}/{_n}"
                for _k in sorted(_all_keys)
            }

            _LOGGER.debug(
                "iRobot cloud: raw_history len=%d\n"
                "  field_coverage: %s\n"
                "  array_stats: %s\n"
                "  nested_keys: %s\n"
                "  first_record: %s\n"
                "  second_record: %s\n"
                "  for %s",
                len(raw_history),
                _coverage_summary,
                _array_stats,
                {_k: sorted(_v) for _k, _v in _nested_keys.items()},
                _first,
                _second,
                self.blid,
            )
        elif isinstance(raw_history, dict):
            _first = raw_history
            _LOGGER.debug(
                "iRobot cloud: raw_history dict_record=%s for %s",
                raw_history, self.blid,
            )
        else:
            _first = {}
            _LOGGER.debug(
                "iRobot cloud: raw_history unexpected type=%s for %s",
                type(raw_history).__name__, self.blid,
            )

        if isinstance(raw_history, list):
            if raw_history:
                # Store raw per-mission records for v2.0 sensors and REST API.
                # Each record preserves all 28 confirmed fields from the API
                # (startTime, timestamp, sqft, done, done_raw, pauseId, wlBars, etc.)
                # A pre-computed "classified_result" field is added so consumers
                # don't need to call classify_mission_result() themselves.
                result["mission_history_raw"] = [
                    {**r, "classified_result": classify_mission_result(r)}
                    for r in raw_history
                    if isinstance(r, dict)
                ]
                # Aggregate ALL records for lifetime totals.
                result["mission_history"] = _aggregate_history(raw_history)
                _LOGGER.debug(
                    "iRobot cloud: aggregated %d mission records -> "
                    "nMssn=%s hr=%s sqft=%s for %s",
                    len(raw_history),
                    result["mission_history"].get("bbmssn", {}).get("nMssn"),
                    result["mission_history"].get("runtimeStats", {}).get("hr"),
                    result["mission_history"].get("runtimeStats", {}).get("sqft"),
                    self.blid,
                )
            else:
                result["mission_history"] = {}
                result["mission_history_raw"] = []
        elif isinstance(raw_history, dict):
            # Some account types may return a summary dict directly.
            result["mission_history"] = _normalize_mission_history(raw_history)
        else:
            result["mission_history"] = {}
            _LOGGER.warning(
                "iRobot cloud: unexpected mission_history type %s for %s",
                type(raw_history).__name__, self.blid,
            )

        # Log pmap structure to answer: does activeDetails=2 embed polygon
        # geometry, or does that require the separate /umf endpoint?
        for _p in result["pmaps"]:
            _det = _p.get("active_pmapv_details", {})
            _pmapv = _det.get("active_pmapv", {})
            _regions = _det.get("regions", [])
            # Determine which key holds the region ID — critical for CR4 attributes.
            # The API uses "region_id" in some account types, "id" in others.
            _rid_key = "region_id" if _regions and "region_id" in _regions[0] else "id"
            _LOGGER.debug(
                "iRobot cloud: pmap_id=%s  pmapv_keys=%s  "
                "region_count=%d  zone_count=%d  "
                "region_id_key=%s  first_region_keys=%s  map_header_keys=%s",
                _pmapv.get("pmap_id"),
                sorted(_pmapv.keys()),
                len(_regions),
                len(_det.get("zones", [])),
                _rid_key,
                sorted(_regions[0].keys()) if _regions else [],
                sorted(_det.get("map_header", {}).keys()),
            )

        _LOGGER.debug(
            "iRobot cloud: fetched %d pmap(s), %d favorite(s) for %s (has_pmaps=%s)",
            len(result["pmaps"]),
            len(result["favorites"]),
            self.blid,
            self._has_pmaps,
        )

        # F9 / F22a — fetch UMF floor plan for SMART robots with active pmaps.
        # Skips gracefully on any error — map data is non-critical.
        if self._has_pmaps and result["pmaps"]:
            try:
                umf_data = await self._fetch_active_umf(result["pmaps"])
                if umf_data:
                    result["umf"] = umf_data
                    _LOGGER.debug(
                        "iRobot cloud: UMF fetched — keepoutzones=%d "
                        "observed_zones=%d points2d=%d for %s",
                        len(umf_data.get("keepoutzones", [])),
                        len(umf_data.get("observed_zones", [])),
                        len(umf_data.get("points2d", [])),
                        self.blid,
                    )
            except Exception:  # noqa: BLE001
                _LOGGER.debug(
                    "iRobot cloud: UMF fetch failed for %s — "
                    "obstacle data unavailable this cycle",
                    self.blid,
                )

        # CR3 — when cloud mission history is empty but MissionStore has enriched
        # records (from a previous successful cloud fetch + merge), serve them as
        # raw_records fallback so CloudRawSensor entities remain available.
        if not result["mission_history_raw"] and self._mission_store is not None:
            fallback = [
                r for r in self._mission_store._records
                if any(r.get(f) is not None for f in ("dirt", "chrgM", "wlBars"))
            ]
            if fallback:
                result["mission_history_raw"] = list(reversed(fallback))
                _LOGGER.debug(
                    "iRobot cloud: CR3 fallback — serving %d enriched "
                    "MissionStore record(s) as raw_records for %s",
                    len(fallback), self.blid,
                )

        return result

    # ── Helpers used by platforms ─────────────────────────────────────────────

    @property
    def raw_records(self) -> list[dict[str, Any]]:
        """Return the raw per-mission records from the last /missionhistory fetch.

        Records are ordered newest-first (as returned by the API).
        Each record contains all confirmed fields: startTime, timestamp, sqft,
        done, done_raw, pauseId, wlBars, runM, chrgs, evacs, dirt, initiator, etc.

        Returns an empty list when no cloud data is available or the API
        returned an empty/non-list response.
        """
        if not self.data:
            return []
        return self.data.get("mission_history_raw", [])

    @property
    def active_pmap_id(self) -> str | None:
        """Return the pmap_id of the first active pmap, or None."""
        if not self.data:
            return None
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            pid = pmapv.get("pmap_id")
            if pid:
                return pid
        return None

    @property
    def regions(self) -> list[dict[str, Any]]:
        """Return regions from the ACTIVE pmap only.

        Deliberately ignores disabled/old maps to prevent room-name collisions
        when multiple Smart Maps exist in the same iRobot account. A user with
        an old disabled map and a current map that share room names would
        otherwise get silent wrong-map cleans (Case 1) or rooms_different_floors
        errors (Case 2) from _resolve_rooms.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            if pmapv.get("pmap_id") != active_id:
                continue  # skip disabled / inactive maps
            regions_raw = details.get("regions", [])
            if not regions_raw:
                return []
            # The iRobot pmaps API uses "region_id" as the identifier key
            # in some account/firmware variants, and "id" in others.
            # Try both to be robust — confirmed as a real divergence from
            # live debug data (June 2026): first_region_keys determines which
            # is present. An empty id silently breaks CR4 attribute generation.
            def _rid(r: dict) -> str:
                return str(r.get("region_id") or r.get("id") or "")

            return [
                {
                    "id":          _rid(region),
                    "name":        region.get("name", ""),
                    "region_type": region.get("region_type", "default"),
                    "pmap_id":     active_id,
                }
                for region in regions_raw
                if _rid(region)   # skip entries with no resolvable ID
            ]
        return []

    @property
    def zones(self) -> list[dict[str, Any]]:
        """Return custom zones from the ACTIVE pmap only.

        Same active-map filter as regions — prevents stale zone data from
        disabled maps contaminating zone_data lookups.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            if pmapv.get("pmap_id") != active_id:
                continue
            zones_raw = details.get("zones", [])
            if not zones_raw:
                return []

            def _zid(z: dict) -> str:
                return str(z.get("zone_id") or z.get("id") or "")

            return [
                {
                    "id":        _zid(zone),
                    "name":      zone.get("name", ""),
                    "zone_type": zone.get("zone_type", "default"),
                    "pmap_id":   active_id,
                }
                for zone in zones_raw
                if _zid(zone)
            ]
        return []

    # ── v2.2.0 UMF properties (F9 / F22a) ────────────────────────────────────

    @property
    def umf_data(self) -> dict[str, Any]:
        """Return the most recently fetched UMF data, or empty dict."""
        if not self.data:
            return {}
        return self.data.get("umf", {})

    @property
    def keepout_zones(self) -> list[dict[str, Any]]:
        """Return keep-out zones from the active UMF floor plan."""
        return self.umf_data.get("keepoutzones", [])

    @property
    def observed_zone_centroids(self) -> list[dict[str, Any]]:
        """Return observed obstacle zone centroids for GridStore seeding.

        Coordinates are in UMF units (space='umf' tag). Not used for pose-space
        rendering until Q6 coordinate units are confirmed in v2.3.
        """
        centroids = []
        for z in self.umf_data.get("observed_zones", []):
            cx = z.get("cx") or z.get("centroid_x") or z.get("x")
            cy = z.get("cy") or z.get("centroid_y") or z.get("y")
            if cx is not None and cy is not None:
                centroids.append({"x": cx, "y": cy, "space": "umf"})
        return centroids

    async def _fetch_active_umf(
        self, pmaps: list[dict]
    ) -> dict[str, Any] | None:
        """Fetch UMF floor plan for the active pmap.

        Returns a dict with keys:
          keepoutzones:   list of keep-out zone dicts (with centroid coords)
          observed_zones: list of robot-learned obstacle dicts (with centroids)
          points2d:       list of wall boundary points (for F8 UmfAligner, v2.3)
          pmap_id:        the pmap_id this UMF belongs to
          version_id:     the pmap version fetched

        Coordinate space: UMF units (Q6 open — store with space='umf' tag,
        do not use for pose-space rendering until Q6 confirmed in v2.3).

        Returns None when no active pmap or UMF fetch fails.
        """
        active_id = self.active_pmap_id
        if not active_id:
            return None

        for pmap in pmaps:
            # Two firmware variants for version_id resolution:
            # Variant A (older): active_pmapv_details.active_pmapv.active_pmapv_id
            # Variant B (lewis 22.52.10): last_user_pmapv_id at pmap root level
            # pmap_id match: either via active_pmapv.pmap_id or directly pmap["pmap_id"]
            details = pmap.get("active_pmapv_details", {})
            pmapv   = details.get("active_pmapv", {})

            # Determine if this pmap matches the active pmap_id
            pmap_id_match = (
                pmapv.get("pmap_id") == active_id      # Variant A
                or pmap.get("pmap_id") == active_id    # Variant B
            )
            if not pmap_id_match:
                continue

            # Resolve version_id — try Variant A first, fall back to Variant B
            version_id = (
                pmapv.get("active_pmapv_id")           # Variant A
                or pmap.get("last_user_pmapv_id")      # Variant B (lewis)
            )
            if not version_id:
                _LOGGER.debug(
                    "iRobot cloud: UMF fetch skipped for %s — "
                    "could not resolve version_id from pmap (keys: %s)",
                    self.blid, list(pmap.keys()),
                )
                return None
            try:
                umf_raw = await self.api.get_pmap_umf(
                    self.blid, active_id, version_id
                )
            except Exception:  # noqa: BLE001
                return None

            return {
                "keepoutzones": [
                    {**z, "space": "umf"}
                    for z in (umf_raw.get("keepoutzones") or [])
                ],
                "observed_zones": [
                    {**z, "space": "umf"}
                    for z in (umf_raw.get("observed_zones") or [])
                ],
                "points2d":  umf_raw.get("points2d") or [],
                "pmap_id":   active_id,
                "version_id": version_id,
            }
        return None
