"""Cloud data coordinator for Roomba+.

Polls the iRobot cloud API once per HA session (at setup) and again whenever
a map retrain is detected via MQTT (user_pmapv_id change). Between those
events the cloud data is stable — pmaps only change when the user physically
retrains or edits room boundaries.

The coordinator is only created for MapCapability.SMART robots AND when the
user has supplied iRobot cloud credentials. All existing local-MQTT behaviour
is completely unaffected when this coordinator is absent.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from datetime import timedelta
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .cloud_api import AuthenticationError, CloudApiError, IrobotCloudApi

_LOGGER = logging.getLogger(__name__)

# Cloud map data changes only on map retrain — poll once per day as a
# backstop; real refresh is triggered by user_pmapv_id MQTT change.
_CLOUD_POLL_INTERVAL = timedelta(hours=24)


class IrobotCloudCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Coordinator for iRobot cloud data (pmaps, mission history, favorites).

    data structure after a successful update:
    {
        "pmaps": [...],          # list of pmap dicts from /pmaps
        "mission_history": {...},# from /missionhistory
        "favorites": [...],      # from /user/favorites
    }
    All keys are always present; they default to empty list/dict on error.
    """

    def __init__(
        self,
        hass: HomeAssistant,
        config_entry: ConfigEntry,
        blid: str,
        username: str,
        password: str,
    ) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"iRobot cloud ({blid})",
            config_entry=config_entry,
            update_interval=_CLOUD_POLL_INTERVAL,
        )
        self.blid = blid
        self.api = IrobotCloudApi(
            username=username,
            password=password,
            session=async_get_clientsession(hass),
        )

    async def _async_setup(self) -> None:
        """Authenticate once when the coordinator is first started."""
        try:
            await self.api.authenticate()
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud credentials are invalid: {exc}"
            ) from exc
        except CloudApiError as exc:
            # Transient — let HA retry via ConfigEntryNotReady pathway
            raise UpdateFailed(f"iRobot cloud setup failed: {exc}") from exc

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch current cloud data for this robot."""
        result: dict[str, Any] = {
            "pmaps": [],
            "mission_history": {},
            "favorites": [],
        }
        try:
            async with asyncio.timeout(30):
                result["pmaps"] = await self.api.get_pmaps(self.blid)
                raw_history = await self.api.get_mission_history(self.blid)
                result["favorites"] = await self.api.get_favorites()
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud authentication failed: {exc}"
            ) from exc
        except CloudApiError as exc:
            raise UpdateFailed(f"iRobot cloud update failed: {exc}") from exc

        # The /missionhistory endpoint returns a list of mission records.
        # The first element contains the accumulated lifetime totals
        # (runtimeStats.sqft, runtimeStats.hr/min, bbmssn.nMssn).
        # Individual mission records follow. We store only the first element
        # (the accumulator) since that is what the lifetime sensors read.
        if isinstance(raw_history, list):
            result["mission_history"] = raw_history[0] if raw_history else {}
        elif isinstance(raw_history, dict):
            # Some firmware versions may return a dict directly — handle gracefully.
            result["mission_history"] = raw_history
        else:
            result["mission_history"] = {}
            _LOGGER.warning(
                "iRobot cloud: unexpected mission_history type %s for %s",
                type(raw_history).__name__, self.blid,
            )

        _LOGGER.debug(
            "iRobot cloud: fetched %d pmap(s), %d favorite(s) for %s",
            len(result["pmaps"]),
            len(result["favorites"]),
            self.blid,
        )
        return result

    # ── Helpers used by platforms ─────────────────────────────────────────────

    @property
    def active_pmap_id(self) -> str | None:
        """Return the pmap_id of the first active pmap, or None."""
        if not self.data:
            return None
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            pid = pmapv.get("pmap_id")
            if pid:
                return pid
        return None

    @property
    def regions(self) -> list[dict[str, Any]]:
        """Return all regions across all pmaps (name, id, pmap_id, region_type)."""
        if not self.data:
            return []
        out: list[dict[str, Any]] = []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            pmap_id = pmapv.get("pmap_id", "")
            for region in details.get("regions", []):
                out.append({
                    "id": region.get("id", ""),
                    "name": region.get("name", ""),
                    "region_type": region.get("region_type", "default"),
                    "pmap_id": pmap_id,
                })
        return out

    @property
    def zones(self) -> list[dict[str, Any]]:
        """Return all custom zones across all pmaps."""
        if not self.data:
            return []
        out: list[dict[str, Any]] = []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            pmap_id = pmapv.get("pmap_id", "")
            for zone in details.get("zones", []):
                out.append({
                    "id": zone.get("id", ""),
                    "name": zone.get("name", ""),
                    "zone_type": zone.get("zone_type", "default"),
                    "pmap_id": pmap_id,
                })
        return out
