"""Maintenance Store for Roomba+ — persists part-reset timestamps.

When a user replaces the filter, brushes, or battery, they press the
corresponding Reset button or call the named service. This store records:
  - The bbrun.hr value at the moment of reset (for remaining-hours calc)
  - The wall-clock ISO datetime at the moment of reset (for timestamp sensors)

Storage is per config-entry in hass.storage so it survives HA restarts
and integration reloads.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from collections.abc import Mapping

from typing import Any

import logging
import statistics
from dataclasses import dataclass, field

from homeassistant.core import HomeAssistant

from .const import (
    CONF_BRUSH_HOURS,
    CONF_FILTER_HOURS,
    DEFAULT_BRUSH_HOURS,
    DEFAULT_FILTER_HOURS,
    IROBOT_PART_ROLE_TO_STORE_SLOT,
    is_mop,
    part_role,
)
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_maintenance"
STORAGE_VERSION    = 1


def _iso_from_epoch(ts: Any) -> str | None:
    """Convert an epoch-seconds reset timestamp to a local ISO-8601 string.

    iRobot's parts endpoint reports `last_updated_ts` in epoch seconds, and
    omits it entirely for a part that has never been reset. Returns None for
    that case and for any unparseable value, so a missing timestamp leaves
    the store's existing value untouched instead of blanking it.
    """
    if ts is None:
        return None
    try:
        epoch = int(ts)
    except (TypeError, ValueError):
        return None
    if epoch <= 0:
        return None
    return dt_util.utc_from_timestamp(epoch).astimezone(dt_util.DEFAULT_TIME_ZONE).isoformat()


@dataclass
class MaintenanceStore:
    """Stores the bbrun.hr value and wall-clock time at each part reset.

    All _hr values in hours (integer, matching bbrun.hr).
    All _reset_at values are ISO-8601 strings or None (pre-v1.7 installs).
    Default 0 / None = never reset.
    """

    # Reset reference points (hours)
    filter_reset_hr: int = 0
    brush_reset_hr: int  = 0
    battery_reset_hr: int = 0

    # Wall-clock timestamps — None until first reset after v1.7.0
    # Surfaces as HA state "unknown" until then, which is correct.
    filter_reset_at: str | None = None
    brush_reset_at: str | None = None
    battery_reset_at: str | None = None

    # F5d — baseline estCap (mAh) recorded on first observation.
    # Used to compute battery_capacity_retention as pct of original capacity.
    # None until the first MQTT message containing bbchg3.estCap is processed.
    baseline_estcap: float | None = None

    # F6g — consecutive scheduled clean opportunities missed (blocked or skipped).
    # Incremented by BlockingManager on timeout; reset to 0 on any completed mission.
    consecutive_skips: int = 0

    # L2 — replacement history for self-calibrating lifespan (v2.5.0).
    filter_reset_history: list[int] = field(default_factory=list)
    brush_reset_history: list[int] = field(default_factory=list)

    # v3.4.1 MAINTENANCE-COLD-START — tracks whether filter_reset_hr/
    # brush_reset_hr have already been auto-seeded to the robot's runtime
    # hours on first-ever load (see __init__.py's async setup). Distinct
    # from filter_reset_history/brush_reset_history, which only ever
    # records REAL user-confirmed resets — this flag exists specifically
    # so the auto-seed step fires exactly once per robot, not on every
    # restart, without polluting the learned-wear-rate history with a
    # synthetic, non-user-confirmed "reset" event.
    filter_baseline_seeded: bool = False
    brush_baseline_seeded: bool = False

    # Cloud consumable state, keyed by iRobot `part_id`. Written by
    # hydrate_from_cloud_parts() from /v1/robots/{blid}/parts and read by
    # the per-part cloud sensors. Held here rather than only in the
    # coordinator so the last known values survive a cloud outage and an
    # HA restart, matching how every other maintenance figure behaves.
    cloud_parts: dict[str, dict[str, Any]] = field(default_factory=dict)
    cloud_parts_hydrated_at: str | None = None

    # IA74-MAINT (v2.6.0) — clean/inspect timestamps (calendar-based, no bbrun.hr)
    wheel_cleaned_at: str | None = None
    contact_cleaned_at: str | None = None
    bin_cleaned_at: str | None = None

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted reset values from hass.storage."""
        store: Store[dict[str, Any]] = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict[str, Any] | None = await store.async_load()
        if not data:
            _LOGGER.debug("MaintenanceStore: no persisted data for %s", entry_id)
            return
        try:
            self.filter_reset_hr  = int(data.get("filter_reset_hr",  0))
            self.brush_reset_hr   = int(data.get("brush_reset_hr",   0))
            self.battery_reset_hr = int(data.get("battery_reset_hr", 0))
            # New in v1.7.0 — None for pre-upgrade installs (backward compat)
            self.filter_reset_at  = data.get("filter_reset_at")
            self.brush_reset_at   = data.get("brush_reset_at")
            self.battery_reset_at = data.get("battery_reset_at")
            # F5d — None until first estCap observation (v2.1+)
            raw_estcap = data.get("baseline_estcap")
            self.baseline_estcap = float(raw_estcap) if raw_estcap is not None else None
            # F6g — 0 for pre-v2.1 installs
            self.consecutive_skips = int(data.get("consecutive_skips", 0))
            # L2: restore replacement history (empty list for pre-v2.5 installs)
            self.filter_reset_history = [
                int(h) for h in data.get("filter_reset_history", [])
            ]
            self.brush_reset_history = [
                int(h) for h in data.get("brush_reset_history", [])
            ]
            # v3.4.1 MAINTENANCE-COLD-START — False for pre-v3.4.1 installs
            # (backward compat: treated as "not yet seeded", matching a
            # fresh store — correct, since this flag didn't exist before
            # and no seeding could have happened yet).
            self.filter_baseline_seeded = bool(data.get("filter_baseline_seeded", False))
            self.brush_baseline_seeded  = bool(data.get("brush_baseline_seeded",  False))
            # Cloud consumable state — absent on installs that predate
            # cloud parts hydration, and absent for robots whose account
            # does not serve the endpoint. Both are "no cloud truth yet".
            raw_cloud_parts = data.get("cloud_parts")
            self.cloud_parts = (
                {str(k): dict(v) for k, v in raw_cloud_parts.items() if isinstance(v, Mapping)}
                if isinstance(raw_cloud_parts, Mapping) else {}
            )
            self.cloud_parts_hydrated_at = data.get("cloud_parts_hydrated_at")
            # IA74-MAINT: calendar-based inspect timestamps
            self.wheel_cleaned_at   = data.get("wheel_cleaned_at")
            self.contact_cleaned_at = data.get("contact_cleaned_at")
            self.bin_cleaned_at     = data.get("bin_cleaned_at")
            _LOGGER.debug(
                "MaintenanceStore: loaded — filter_reset=%dh brush_reset=%dh",
                self.filter_reset_hr, self.brush_reset_hr,
            )
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MaintenanceStore: failed to load data: %s", exc)

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current reset values to hass.storage."""
        store: Store[dict[str, Any]] = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({
            "filter_reset_hr":  self.filter_reset_hr,
            "brush_reset_hr":   self.brush_reset_hr,
            "battery_reset_hr": self.battery_reset_hr,
            "filter_reset_at":  self.filter_reset_at,
            "brush_reset_at":   self.brush_reset_at,
            "battery_reset_at": self.battery_reset_at,
            "baseline_estcap":  self.baseline_estcap,   # F5d
            "consecutive_skips": self.consecutive_skips, # F6g
            "filter_reset_history": self.filter_reset_history,  # L2
            "brush_reset_history":  self.brush_reset_history,   # L2
            "filter_baseline_seeded": self.filter_baseline_seeded,  # v3.4.1
            "brush_baseline_seeded":  self.brush_baseline_seeded,   # v3.4.1
            "cloud_parts": self.cloud_parts,
            "cloud_parts_hydrated_at": self.cloud_parts_hydrated_at,
            # IA74-MAINT
            "wheel_cleaned_at":   self.wheel_cleaned_at,
            "contact_cleaned_at": self.contact_cleaned_at,
            "bin_cleaned_at":     self.bin_cleaned_at,
        })

    # ── Reset methods ─────────────────────────────────────────────────────────

    def reset_filter(self, current_hr: int) -> None:
        """Record current bbrun.hr and wall-clock time as filter replacement point.

        L2: appends to filter_reset_history for self-calibrating lifespan.
        After 2+ replacements, learned_filter_hours provides the personal interval.
        """
        # L2: record history before updating reset_hr so the interval is computable
        self.filter_reset_history.append(current_hr)
        self.filter_reset_hr = current_hr
        self.filter_reset_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: filter reset at %dh (history len=%d)",
                     current_hr, len(self.filter_reset_history))

    def reset_brush(self, current_hr: int) -> None:
        """Record current bbrun.hr and wall-clock time as brush replacement point.

        L2: appends to brush_reset_history for self-calibrating lifespan.
        After 2+ replacements, learned_brush_hours provides the personal interval.
        """
        # L2: record history before updating reset_hr
        self.brush_reset_history.append(current_hr)
        self.brush_reset_hr = current_hr
        self.brush_reset_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: brush reset at %dh (history len=%d)",
                     current_hr, len(self.brush_reset_history))

    def reset_battery(self, current_hr: int) -> None:
        """Record current bbrun.hr and wall-clock time as battery replacement point."""
        self.battery_reset_hr = current_hr
        self.battery_reset_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: battery reset at %dh", current_hr)

    def reset_pad(self, current_hr: int) -> None:
        """Braava alias for reset_brush — pad and brush share the same store slot."""
        self.brush_reset_history.append(current_hr)
        self.brush_reset_hr = current_hr
        self.brush_reset_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: pad reset at %dh", current_hr)

    # ── Cloud hydration ───────────────────────────────────────────────────────

    def hydrate_from_cloud_parts(
        self, parts: list[dict[str, Any]], current_hr: int
    ) -> bool:
        """Adopt iRobot's own consumable counters as this store's baseline.

        THE POINT OF THIS METHOD IS MIGRATION. Without it, a robot that has
        been in service for months before this integration was installed
        gets its maintenance baseline from the cold-start seed, which
        assumes every consumable is fresh as of install time. That is
        wrong for exactly the users most likely to install this — and it
        is why the remaining-hours sensors can read a full budget on a
        robot whose filter is nearly due, and why the days-until-due
        sensors sit at "unknown" with no wear history to extrapolate from.

        The cloud knows better, because the official app writes to it: a
        part's `count_used` is robot runtime minutes since that part was
        last reset, including resets the user performed in the app. So the
        bbrun.hr reading at the moment of that reset is recoverable:

            reset_hr = current_hr - count_used / 60

        Every part is recorded in `cloud_parts` verbatim, keyed by id, with
        no interpretation — the per-part sensors read that and therefore
        never depend on the id->role guess. Only the two roles the legacy
        filter/brush slots model are additionally mapped onto those slots,
        and only when the role is known; an unrecognised id updates
        `cloud_parts` and nothing else, so a mis-mapped id can never write
        a wrong baseline into the store.

        `*_reset_history` is deliberately NOT appended to. That list feeds
        the learned-lifespan median and means "a replacement the user
        confirmed"; the cloud exposes only the most recent reset per part,
        so appending would invent a single synthetic interval and bias the
        learned figure. Hydration sets the baseline; real resets keep
        building the history from there.

        Returns True when anything changed, so the caller knows whether a
        save is needed.
        """
        changed = False
        for entry in parts:
            part_id = entry.get("part_id")
            if part_id is None:
                continue
            key = str(part_id).strip()

            snapshot = {
                "part_id": key,
                "count_used": entry.get("count_used"),
                "count_remaining": entry.get("count_remaining"),
                "minutes_remaining": entry.get("minutes_remaining"),
                "counter": entry.get("counter"),
                "count_type": entry.get("count_type"),
                "counter_category": entry.get("counter_category"),
                "last_updated_ts": entry.get("last_updated_ts"),
                "reset_by": entry.get("reset_by"),
                "role": part_role(key),
            }
            if self.cloud_parts.get(key) != snapshot:
                self.cloud_parts[key] = snapshot
                changed = True

            slot = IROBOT_PART_ROLE_TO_STORE_SLOT.get(snapshot["role"] or "")
            if slot is None:
                continue

            # Only minute-denominated counters are convertible to the
            # bbrun.hr domain the legacy slots live in. Anything else
            # (a hypothetical mission-count or fill-count counter) is
            # left alone rather than silently misread as minutes.
            if entry.get("count_type") != "minutes":
                continue
            try:
                used_hr = int(int(entry["count_used"]) // 60)
            except (KeyError, TypeError, ValueError):
                continue

            reset_hr = max(0, int(current_hr) - used_hr)
            reset_at = _iso_from_epoch(entry.get("last_updated_ts"))

            if getattr(self, f"{slot}_reset_hr") != reset_hr:
                setattr(self, f"{slot}_reset_hr", reset_hr)
                changed = True
            # A part that has never been reset carries no timestamp; keep
            # whatever the store already had rather than blanking it.
            if reset_at is not None and getattr(self, f"{slot}_reset_at") != reset_at:
                setattr(self, f"{slot}_reset_at", reset_at)
                changed = True
            # The cold-start seed must not later overwrite a real cloud
            # baseline with the install-time assumption.
            if not getattr(self, f"{slot}_baseline_seeded"):
                setattr(self, f"{slot}_baseline_seeded", True)
                changed = True

        if changed:
            self.cloud_parts_hydrated_at = dt_util.now().isoformat()
            _LOGGER.info(
                "MaintenanceStore: hydrated %d cloud part(s) at %dh runtime "
                "(filter_reset=%dh brush_reset=%dh)",
                len(parts), current_hr, self.filter_reset_hr, self.brush_reset_hr,
            )
        return changed

    # ── IA74-MAINT (v2.7.0) — calendar-based inspect resets ──────────────────
    # These components have no bbrun.hr lifecycle — they are cleaned on a
    # calendar cadence, not an hours-of-use basis.  Only the wall-clock
    # timestamp is recorded so the sensor can show "last cleaned" and users
    # can build reminders from it.

    def reset_wheel_cleaning(self) -> None:
        """Record wall-clock time as the wheel-module last-cleaned timestamp."""
        self.wheel_cleaned_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: wheel cleaning reset at %s", self.wheel_cleaned_at)

    def reset_contact_cleaning(self) -> None:
        """Record wall-clock time as the charging-contact last-cleaned timestamp."""
        self.contact_cleaned_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: contact cleaning reset at %s", self.contact_cleaned_at)

    def reset_bin_cleaning(self) -> None:
        """Record wall-clock time as the bin last-cleaned timestamp."""
        self.bin_cleaned_at = dt_util.now().isoformat()
        _LOGGER.info("MaintenanceStore: bin cleaning reset at %s", self.bin_cleaned_at)

    # ── F5d — Battery capacity baseline ──────────────────────────────────────

    def record_estcap_if_needed(self, estcap_mah: float) -> bool:
        """Record converted mAh capacity as baseline on first valid observation.

        F5d — called by battery_capacity_retention sensor on every MQTT update.
        Receives the *converted* mAh value (raw estCap ÷ chemistry scale),
        NOT the raw BMS value.  Only sets the baseline once; subsequent calls
        are no-ops so the baseline never drifts once established.

        Returns True when the baseline was just set for the first time so the
        caller can schedule async_save() to persist the value immediately.
        """
        if self.baseline_estcap is None and estcap_mah > 0:
            self.baseline_estcap = float(estcap_mah)
            _LOGGER.info(
                "MaintenanceStore: baseline_estcap set to %.0f mAh "
                "(converted from raw BMS value)", estcap_mah
            )
            return True
        return False

    # ── L2 — Self-calibrating lifespan ───────────────────────────────────────

    @property
    def learned_filter_hours(self) -> float | None:
        """Median interval between filter replacements, or None if < 2 resets.

        L2: after 2+ replacements, returns the personal filter lifespan.
        Exposed in diagnostics. Used by filter_remaining when available.
        """
        if len(self.filter_reset_history) < 2:
            return None
        intervals = [
            self.filter_reset_history[i] - self.filter_reset_history[i - 1]
            for i in range(1, len(self.filter_reset_history))
            if self.filter_reset_history[i] > self.filter_reset_history[i - 1]
        ]
        return statistics.median(intervals) if intervals else None

    @property
    def learned_brush_hours(self) -> float | None:
        """Median interval between brush replacements, or None if < 2 resets.

        L2: after 2+ replacements, returns the personal brush lifespan.
        Exposed in diagnostics. Used by brush_remaining when available.
        """
        if len(self.brush_reset_history) < 2:
            return None
        intervals = [
            self.brush_reset_history[i] - self.brush_reset_history[i - 1]
            for i in range(1, len(self.brush_reset_history))
            if self.brush_reset_history[i] > self.brush_reset_history[i - 1]
        ]
        return statistics.median(intervals) if intervals else None

    # ── Remaining-life calculations ───────────────────────────────────────────

    def due_items(
        self, vacuum_state: Mapping[str, Any], options: Mapping[str, Any]
    ) -> list[str]:
        """v3.4.3 FLEET-1 — return consumable keys currently at zero
        remaining hours.

        Extracted from binary_sensor.py's RoombaMaintenanceDue._due_items()
        (identical logic, now shared) so the household REST endpoint's
        fleet-health rollup can report the same "is maintenance due"
        signal without duplicating the threshold/mop-vs-vacuum-key logic
        a second time. binary_sensor.py's _due_items() now delegates here.
        """
        current_hr = (vacuum_state.get("bbrun") or {}).get("hr", 0)
        items: list[str] = []
        if self.filter_remaining(
            current_hr, options.get(CONF_FILTER_HOURS, DEFAULT_FILTER_HOURS)
        ) == 0:
            items.append("filter")
        brush_key = "pad" if is_mop(dict(vacuum_state)) else "brush"
        if self.brush_remaining(
            current_hr, options.get(CONF_BRUSH_HOURS, DEFAULT_BRUSH_HOURS)
        ) == 0:
            items.append(brush_key)
        return items

    def filter_remaining(self, current_hr: int, threshold: int) -> int:
        """Hours remaining until next filter replacement.

        L2: uses learned_filter_hours when available (after 2+ replacements),
        falling back to the configured threshold otherwise.
        Uses round() not int() to avoid systematic truncation error (up to 59 min).
        """
        effective = round(self.learned_filter_hours or threshold)
        hours_since_reset = current_hr - self.filter_reset_hr
        return max(0, effective - hours_since_reset)

    def brush_remaining(self, current_hr: int, threshold: int) -> int:
        """Hours remaining until next brush/pad replacement.

        L2: uses learned_brush_hours when available (after 2+ replacements),
        falling back to the configured threshold otherwise.
        Uses round() not int() to avoid systematic truncation error (up to 59 min).
        """
        effective = round(self.learned_brush_hours or threshold)
        hours_since_reset = current_hr - self.brush_reset_hr
        return max(0, effective - hours_since_reset)
