"""MissionTimerStore — persists mission run-time across HA restarts.

MP1 (v2.6.0) — a purely transient counter is lost on HA restart mid-mission,
producing misleading 0 % progress. This store persists the current mission_id
and accumulated run_sec to hass.storage so the progress sensor can resume
from the correct value after a restart.

v2.7.1 (MP-PERSIST) — extended schema: also persists total_estimated_sec
(prevents progress ratio jump after restart), planned_rooms + current_room_idx
(prevents current_room/next_room freeze on lewis firmware that doesn't re-send
plan events after MQTT reconnect), recharge_positions (for ⚡ markers),
and snapshot_ts (staleness gate: if now - snapshot_ts > 7200 s the timer is
stale and is discarded rather than resumed).

Lifecycle:
  - Instantiated in async_setup_entry for SMART + cloud robots.
  - Call async_load() on setup to resume any in-progress mission.
  - Call set_mission_plan() at mission start to write total_estimated_sec
    and planned_rooms.
  - Call on_phase_run() on every phase=="run" MQTT message to accumulate.
  - Call advance_room() when a traversal event changes the current room.
  - Call on_recharge() when a recharge event is detected.
  - Call clear() when mission_id changes or mission ends.
  - async_save() is called automatically after mutations.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import asyncio
import time
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

_LOGGER = logging.getLogger(__name__)

STORAGE_VERSION = 1
_STORAGE_KEY_PREFIX = "roomba_plus_mission_timer"
_STALE_THRESHOLD_SEC = 7200  # 2 hours — if snapshot is older, timer is stale


class MissionTimerStore:
    """Persist elapsed run-only seconds and mission plan for the active mission.

    Fields stored (v2.7.1):
        mission_id: str | None        — current mission identifier (blid + start_ts)
        run_sec: float                — accumulated run-only seconds
        total_estimated_sec: float|None — estimated total cleaning time (denominator)
        planned_rooms: list[str]      — room names in planned order
        current_room_idx: int         — last known position in planned_rooms
        recharge_positions: list[int] — indices in planned_rooms where recharges occurred
        snapshot_ts: float            — wall-clock time of last write (staleness gate)
    """

    def __init__(self) -> None:
        self.mission_id: str | None = None
        self.run_sec: float = 0.0
        self.total_estimated_sec: float | None = None
        self.planned_rooms: list[str] = []
        self.current_room_idx: int = 0
        self.recharge_positions: list[int] = []
        self.snapshot_ts: float = 0.0
        self._last_phase_ts: float = 0.0

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted timer from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            return
        try:
            snapshot_ts = float(data.get("snapshot_ts", 0))
            # Staleness gate: discard if snapshot is older than 2 hours.
            if snapshot_ts and (time.time() - snapshot_ts) > _STALE_THRESHOLD_SEC:
                _LOGGER.debug(
                    "MissionTimerStore: stale snapshot (%.0f s old) — discarding",
                    time.time() - snapshot_ts,
                )
                return
            self.mission_id           = data.get("mission_id")
            self.run_sec              = float(data.get("run_sec", 0))
            self.total_estimated_sec  = data.get("total_estimated_sec")
            self.planned_rooms        = data.get("planned_rooms") or []
            self.current_room_idx     = int(data.get("current_room_idx", 0))
            self.recharge_positions   = data.get("recharge_positions") or []
            self.snapshot_ts          = snapshot_ts
            _LOGGER.debug(
                "MissionTimerStore: resumed mission=%s run_sec=%.0f rooms=%s idx=%d",
                self.mission_id, self.run_sec,
                self.planned_rooms, self.current_room_idx,
            )
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionTimerStore: load failed — %s", exc)

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current timer state."""
        store = Store(hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({
            "mission_id":          self.mission_id,
            "run_sec":             self.run_sec,
            "total_estimated_sec": self.total_estimated_sec,
            "planned_rooms":       self.planned_rooms,
            "current_room_idx":    self.current_room_idx,
            "recharge_positions":  self.recharge_positions,
            "snapshot_ts":         time.time(),
        })

    def _schedule_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Thread-safe async save (safe to call from paho-MQTT thread)."""
        asyncio.run_coroutine_threadsafe(
            self.async_save(hass, entry_id),
            hass.loop,
        )

    # ── Public API ────────────────────────────────────────────────────────────

    def set_mission_plan(
        self,
        mission_id: str,
        planned_rooms: list[str],
        total_estimated_sec: float | None,
        hass: HomeAssistant,
        entry_id: str,
    ) -> None:
        """Called at mission start with the planned room sequence and time estimate.

        MP-PERSIST: persisting these values means that after an HA restart,
        current_room/next_room remain correct and progress ratio stays stable.
        """
        if self.mission_id != mission_id:
            self.mission_id          = mission_id
            self.run_sec             = 0.0
            self.current_room_idx    = 0
            self.recharge_positions  = []
            self._last_phase_ts      = 0.0
        self.planned_rooms       = planned_rooms
        self.total_estimated_sec = total_estimated_sec
        self._schedule_save(hass, entry_id)

    def on_recharge(self, hass: HomeAssistant, entry_id: str) -> None:
        """Called when a recharge event is detected mid-mission.

        Records the current room index so the traversal display can insert
        a ⚡ marker at the right position.
        """
        if self.current_room_idx not in self.recharge_positions:
            self.recharge_positions.append(self.current_room_idx)
        self._schedule_save(hass, entry_id)

    def on_phase_run(self, mission_id: str, hass: HomeAssistant, entry_id: str) -> None:
        """Called each time phase=="run" is observed in MQTT.

        Accumulates elapsed wall-clock delta since the previous phase=="run"
        message. Ignores inter-message gaps > 120 s (e.g. recharges, pauses,
        HA restarts) to avoid double-counting non-cleaning time.

        Saves asynchronously via asyncio.run_coroutine_threadsafe (thread-safe;
        called from paho-MQTT thread via callbacks.py) to avoid blocking
        the MQTT callback loop.
        """
        now = time.monotonic()
        if self.mission_id != mission_id:
            # New mission — reset counter (plan set separately via set_mission_plan)
            self.mission_id      = mission_id
            self.run_sec         = 0.0
            self._last_phase_ts  = now
            self._schedule_save(hass, entry_id)
            return

        if self._last_phase_ts > 0:
            delta = now - self._last_phase_ts
            # Clamp: ignore gaps > 120 s (recharge, pause, restart)
            if 0 < delta < 120:
                self.run_sec += delta
                self._schedule_save(hass, entry_id)
        self._last_phase_ts = now

    def on_phase_other(
        self,
        hass: HomeAssistant | None = None,
        entry_id: str | None = None,
    ) -> None:
        """Flush pending live delta into run_sec then reset the phase timestamp.

        v2.7.5 (MP-TRANSITION-FIX): previously discarded the delta accumulated
        since the last phase=run message.  Lewis firmware sends a non-run
        cleanMissionStatus at every inter-room boundary, so each room transition
        caused elapsed_run_min and progress to jump backwards to the bare
        run_sec value, then recover once phase=run resumed in the next room.

        The flush uses the same 120 s cap as on_phase_run to exclude genuine
        long pauses (recharges, stuck events) where the gap is intentionally
        not counted as run time.

        hass and entry_id are optional so callers that cannot provide them
        (e.g. tests) still work; without them the flushed value is persisted
        on the next on_phase_run call instead.
        """
        now = time.monotonic()
        if self._last_phase_ts > 0:
            delta = now - self._last_phase_ts
            if 0 < delta < 120:
                self.run_sec += delta
                if hass is not None and entry_id is not None:
                    self._schedule_save(hass, entry_id)
        self._last_phase_ts = 0.0

    def clear(self, hass: HomeAssistant, entry_id: str) -> None:
        """Reset the timer at mission end. Saves asynchronously."""
        self.mission_id          = None
        self.run_sec             = 0.0
        self.total_estimated_sec = None
        self.planned_rooms       = []
        self.current_room_idx    = 0
        self.recharge_positions  = []
        self.snapshot_ts         = 0.0
        self._last_phase_ts      = 0.0
        self._schedule_save(hass, entry_id)

    # ── Derived properties (for sensor.py) ────────────────────────────────────

    @property
    def elapsed_run_min(self) -> float | None:
        """Elapsed run time in minutes (float, 1 decimal precision).

        MP-ELAPSED: was int division causing 12 sec → 0 min after restart.
        Now returns float so 12 s shows as 0.2 min.
        """
        if not self.mission_id:
            return None
        return round(self.run_sec / 60, 1)

    @property
    def current_room(self) -> str | None:
        """Current room from restored plan (MP-ROOMS: survives HA restart)."""
        if not self.planned_rooms:
            return None
        idx = min(self.current_room_idx, len(self.planned_rooms) - 1)
        return self.planned_rooms[idx]

    @property
    def next_room(self) -> str | None:
        """Next room from restored plan (MP-ROOMS: survives HA restart)."""
        if not self.planned_rooms:
            return None
        next_idx = self.current_room_idx + 1
        if next_idx >= len(self.planned_rooms):
            return None
        return self.planned_rooms[next_idx]
