"""Mission Store for Roomba+ — append-only mission history log.

Persists up to 365 mission records per robot, keyed by config entry ID.
Provides query, aggregation, and window-analysis methods consumed by
L1 sensors, L3 error intelligence, L6 presence analytics, and the
REST API view.

No HA dependencies at import time — fully unit-testable without stubs.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_missions"
STORAGE_VERSION = 1
MAX_RECORDS = 365


@dataclass(frozen=True)
class DaySummary:
    """Aggregated mission stats for a single calendar day."""

    date: date
    total: int
    completed: int
    stuck: int
    area_sqft: float | None   # sum for day; None if 600-series
    result: str               # dominant: "error" > "stuck" > "completed" > "cancelled" > "none"


@dataclass(frozen=True)
class MissionWindow:
    """A gap between two consecutive missions — potential all-away window."""

    started_at: datetime
    ended_at: datetime
    duration_min: int
    resulted_in_clean: bool   # True if a completed mission started within this window


class MissionStore:
    """Append-only mission log — max 365 records FIFO.

    Lifecycle (must be respected by callers):
      - Instantiate in async_setup_entry.
      - Call async_load() immediately after instantiation.
      - Store in entry.runtime_data.mission_store.
      - No active listeners — no cancel/unload cleanup required.
    """

    def __init__(self) -> None:
        self._records: list[dict[str, Any]] = []

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted records from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            _LOGGER.debug("MissionStore: no persisted data for %s", entry_id)
            return
        try:
            self._records = list(data.get("records", []))
            _LOGGER.debug("MissionStore: loaded %d record(s) for %s", len(self._records), entry_id)
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionStore: failed to load — %s; starting empty", exc)
            self._records = []

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current records to hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({"records": self._records})

    # ── Write ─────────────────────────────────────────────────────────────────

    async def async_append(self, record: dict[str, Any]) -> None:
        """Append a record and trim to MAX_RECORDS FIFO."""
        self._records.append(record)
        if len(self._records) > MAX_RECORDS:
            self._records = self._records[-MAX_RECORDS:]

    # ── Read ──────────────────────────────────────────────────────────────────

    def latest(self) -> dict[str, Any] | None:
        """Return the most recent record, or None."""
        return self._records[-1] if self._records else None

    def query(self, days: int, result: str | None = None) -> list[dict[str, Any]]:
        """Return records from the last `days` days, optionally filtered by result.

        Records are returned sorted ascending by started_at.
        """
        cutoff = dt_util.now() - timedelta(days=days)
        out = []
        for r in self._records:
            started = dt_util.parse_datetime(r.get("started_at", ""))
            if started is None:
                continue
            # Make started timezone-aware for comparison if needed
            if started.tzinfo is None:
                started = started.replace(tzinfo=timezone.utc)
            if started < cutoff:
                continue
            if result is not None and r.get("result") != result:
                continue
            out.append(r)
        return sorted(out, key=lambda r: r.get("started_at", ""))

    def query_by_day(self, days: int) -> dict[date, DaySummary]:
        """Group query(days) results by local calendar date.

        Returns a dict keyed by date. Days with no missions are omitted.
        """
        from collections import defaultdict
        buckets: dict[date, list[dict]] = defaultdict(list)
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt:
                buckets[dt_util.as_local(dt).date()].append(r)

        summaries: dict[date, DaySummary] = {}
        for day, records in buckets.items():
            total = len(records)
            completed = sum(1 for r in records if r.get("result") == "completed")
            stuck = sum(1 for r in records if r.get("result") == "stuck")
            areas = [r["area_sqft"] for r in records if r.get("area_sqft") is not None]
            area_sqft: float | None = float(sum(areas)) if areas else None
            # Dominant result: error > stuck > completed > cancelled > none
            results = {r.get("result") for r in records}
            dominant = (
                "error" if "error" in results else
                "stuck" if "stuck" in results else
                "completed" if "completed" in results else
                "cancelled" if "cancelled" in results else
                "none"
            )
            summaries[day] = DaySummary(
                date=day,
                total=total,
                completed=completed,
                stuck=stuck,
                area_sqft=area_sqft,
                result=dominant,
            )
        return summaries

    def presence_windows(self, days: int) -> list[MissionWindow]:
        """Return gaps between missions as potential 'all-away' windows.

        Each window spans from the end of one mission to the start of the next.
        resulted_in_clean=True when a completed mission started within the window.
        Used by L6 analytics sensors.
        """
        records = self.query(days)
        if len(records) < 2:
            return []

        windows: list[MissionWindow] = []
        completed_starts: set[str] = {
            r["started_at"] for r in records if r.get("result") == "completed"
        }

        for i in range(len(records) - 1):
            prev_end_str = records[i].get("ended_at", "")
            next_start_str = records[i + 1].get("started_at", "")
            prev_end = dt_util.parse_datetime(prev_end_str)
            next_start = dt_util.parse_datetime(next_start_str)
            if prev_end is None or next_start is None:
                continue
            # Make timezone-aware if needed
            if prev_end.tzinfo is None:
                prev_end = prev_end.replace(tzinfo=timezone.utc)
            if next_start.tzinfo is None:
                next_start = next_start.replace(tzinfo=timezone.utc)
            if next_start <= prev_end:
                continue
            duration_min = int((next_start - prev_end).total_seconds() / 60)
            resulted = next_start_str in completed_starts
            windows.append(MissionWindow(
                started_at=prev_end,
                ended_at=next_start,
                duration_min=duration_min,
                resulted_in_clean=resulted,
            ))
        return windows

    def clean_streak(self) -> int:
        """Return consecutive days ending today with at least one completed mission."""
        today = dt_util.now().date()
        completed_dates: set[date] = set()
        for r in self._records:
            if r.get("result") == "completed":
                dt = dt_util.parse_datetime(r.get("started_at", ""))
                if dt:
                    completed_dates.add(dt_util.as_local(dt).date())
        streak = 0
        day = today
        while day in completed_dates:
            streak += 1
            day -= timedelta(days=1)
        return streak
