"""Mission Store for Roomba+ — append-only mission history log.

Persists up to 365 mission records per robot, keyed by config entry ID.
Provides query, aggregation, and window-analysis methods consumed by
L1 sensors, L3 error intelligence, L6 presence analytics, and the
REST API view.

No HA dependencies at import time — fully unit-testable without stubs.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import statistics
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Any, NamedTuple

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

from .const import SQFT_TO_M2

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_missions"
STORAGE_VERSION = 1
MAX_RECORDS = 365


class BackfillResult(NamedTuple):
    """Result of backfill_from_cloud()."""
    corrected: int  # records where timestamps were corrected (delta > 300s)
    enriched: int   # records where analytics fields were merged


# Cloud → local field merge lists for backfill_from_cloud().
# Scalar fields: copied when local value is absent (None or missing).
_CLOUD_MERGE_SCALAR: tuple[str, ...] = (
    "chrgM",     # recharge minutes — F5c source
    "dirt",      # dirt events — F5b source
    "sqft",      # raw area (area_sqft is the canonical local name)
    "runM",      # actual cleaning minutes (excl. recharge)
    "durationM", # total mission minutes
    "chrgs",     # mid-mission recharge count
    "evacs",     # bin evacuations
    "nMssn",     # lifetime mission counter at this mission
    "timeline",  # full mission event log (dict: plan + finEvents) — CR4 source
                 # Field confirmed as 'timeline' from CR3 debug (June 2026).
                 # Contains plan.upcoming (planned room order) and finEvents
                 # (room/travel/traversal/evac/charge events per room).
                 # dict, not a list — lives in _CLOUD_MERGE_SCALAR, not ARRAY.
    # Amendment 8f — confirmed useful from Thonno's 75-record dataset (June 2026)
    "dockedAtStart",  # bool  — was robot docked at mission start?
    "missionId",      # str   — cloud ULID, stable dedup key across reboots
    "pauseM",         # int   — minutes spent paused (non-charging, non-cleaning)
    "cmd",            # dict  — full start command incl. per-room twoPass params
)

# Array fields: copied when local value is absent or empty list.
_CLOUD_MERGE_ARRAY: tuple[str, ...] = (
    "wlBars",    # per-mission WiFi signal histogram (5-element) — F1 source
                 # startEndWlBars (scalar bar-strength at start/end) is a
                 # separate top-level field; not merged (redundant with wlBars).
)


@dataclass(frozen=True)
class DaySummary:
    """Aggregated mission stats for a single calendar day."""

    date: date
    total: int
    completed: int
    stuck: int
    area_sqft: float | None   # sum for day; None if 600-series
    result: str               # dominant: "error" > "stuck" > "completed" > "cancelled" > "none"
    dirt_density: float | None = None  # F12b — median dirt events/m² for day; None without cloud


@dataclass(frozen=True)
class MissionWindow:
    """A gap between two consecutive missions — potential all-away window."""

    started_at: datetime
    ended_at: datetime
    duration_min: int
    resulted_in_clean: bool   # True if a completed mission started within this window


class MissionStore:
    """Append-only mission log — max 365 records FIFO.

    Lifecycle (must be respected by callers):
      - Instantiate in async_setup_entry.
      - Call async_load() immediately after instantiation.
      - Store in entry.runtime_data.mission_store.
      - No active listeners — no cancel/unload cleanup required.
    """

    def __init__(self) -> None:
        self._records: list[dict[str, Any]] = []

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted records from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            _LOGGER.debug("MissionStore: no persisted data for %s", entry_id)
            return
        try:
            self._records = list(data.get("records", []))
            _LOGGER.debug("MissionStore: loaded %d record(s) for %s", len(self._records), entry_id)
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionStore: failed to load — %s; starting empty", exc)
            self._records = []

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current records to hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({"records": self._records})

    # ── Write ─────────────────────────────────────────────────────────────────

    async def async_append(self, record: dict[str, Any]) -> None:
        """Append a record and trim to MAX_RECORDS FIFO.

        F4c — duplicate guard: drops records whose id matches a recent record
        with the same ended_at (= true MQTT re-delivery of the same event).

        v2.6.3 B3 — multi-recharge missions: the 980 firmware keeps the original
        mssnStrtTm across all charging segments, so Segment 2 and Segment 3 of
        a 3-segment mission would share the same record id as Segment 1 and be
        silently dropped by the original guard.  The fix: only drop when BOTH
        id AND ended_at match (true duplicate).  When only the id matches (same
        start_ts, different end = subsequent segment), assign a unique id by
        appending "_r<N>" before storing.
        """
        record_id = record.get("id")
        if record_id:
            for existing in self._records[-5:]:
                if existing.get("id") == record_id:
                    if existing.get("ended_at") == record.get("ended_at"):
                        # True MQTT re-delivery — same start AND same end
                        _LOGGER.debug(
                            "MissionStore: duplicate record %s dropped (MQTT re-delivery)",
                            record_id,
                        )
                        return
                    # Same start_ts, different end = subsequent recharge segment.
                    # Give it a unique id so it is stored alongside segment 1.
                    seg_n = sum(
                        1 for r in self._records
                        if r.get("id", "").startswith(record_id)
                    )
                    record = {**record, "id": f"{record_id}_r{seg_n}"}
                    _LOGGER.debug(
                        "MissionStore: multi-recharge segment stored as %s",
                        record["id"],
                    )
                    break
        self._records.append(record)
        if len(self._records) > MAX_RECORDS:
            self._records = self._records[-MAX_RECORDS:]

    # ── Read ──────────────────────────────────────────────────────────────────

    def latest(self) -> dict[str, Any] | None:
        """Return the most recent record, or None."""
        return self._records[-1] if self._records else None

    # All result values that represent a stuck/failure event.
    STUCK_RESULTS: frozenset[str] = frozenset({
        "stuck", "stuck_and_resumed", "stuck_and_abandoned"
    })
    ERROR_RESULTS: frozenset[str] = frozenset({
        "error", "stuck", "stuck_and_resumed", "stuck_and_abandoned"
    })

    def query(
        self,
        days: int,
        result: str | frozenset[str] | None = None,
    ) -> list[dict[str, Any]]:
        """Return records from the last `days` days, optionally filtered by result.

        ``result`` may be a single string for exact match or a frozenset of
        strings for any-of matching.  Use ``MissionStore.STUCK_RESULTS`` to
        query all stuck variants at once.

        Records are returned sorted ascending by started_at.
        """
        result_set: frozenset[str] | None = (
            None if result is None else
            result if isinstance(result, frozenset) else
            frozenset({result})
        )
        cutoff = dt_util.now() - timedelta(days=days)
        out = []
        for r in self._records:
            started = dt_util.parse_datetime(r.get("started_at", ""))
            if started is None:
                continue
            # Make started timezone-aware for comparison if needed
            if started.tzinfo is None:
                started = started.replace(tzinfo=timezone.utc)
            if started < cutoff:
                continue
            if result_set is not None and r.get("result") not in result_set:
                continue
            out.append(r)
        return sorted(out, key=lambda r: r.get("started_at", ""))

    def query_by_error(
        self,
        error_code: int,
        days: int,
        zone: str | None = None,
    ) -> list[dict[str, Any]]:
        """Return records for a specific error code in the last `days` days.

        F8b — used by the error-recurrence Repair Issue to detect ≥3 occurrences
        of the same error code in the same zone within a lookback window.

        Args:
            error_code: The integer error code to match (cleanMissionStatus.error).
            days:       Lookback window in days.
            zone:       When set, additionally filter by the first zone name.
                        Pass None to return all records regardless of zone.
        """
        results = []
        for r in self.query(days):
            if r.get("error_code") != error_code:
                continue
            if zone is not None:
                zones = r.get("zones") or []
                if not zones or zones[0] != zone:
                    continue
            results.append(r)
        return results

    def query_by_day(self, days: int) -> dict[date, DaySummary]:
        """Group query(days) results by local calendar date.

        Returns a dict keyed by date. Days with no missions are omitted.
        """
        from collections import defaultdict
        buckets: dict[date, list[dict]] = defaultdict(list)
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt:
                buckets[dt_util.as_local(dt).date()].append(r)

        summaries: dict[date, DaySummary] = {}
        for day, records in buckets.items():
            total = len(records)
            # F6h: stuck_and_resumed counts as completed (robot finished);
            # stuck_and_abandoned counts as stuck (mission failed).
            # F6c: blocked_timeout counts as total but not completed.
            completed = sum(
                1 for r in records
                if r.get("result") in ("completed", "stuck_and_resumed")
            )
            stuck = sum(
                1 for r in records
                if r.get("result") in ("stuck", "stuck_and_abandoned")
            )
            areas = [r["area_sqft"] for r in records if r.get("area_sqft") is not None]
            area_sqft: float | None = float(sum(areas)) if areas else None
            # Dominant result: error > stuck > completed > cancelled > none
            results = {r.get("result") for r in records}
            dominant = (
                "error" if "error" in results else
                "stuck" if results & {"stuck", "stuck_and_abandoned"} else
                "completed" if results & {"completed", "stuck_and_resumed"} else
                "cancelled" if "cancelled" in results else
                "none"
            )
            summaries[day] = DaySummary(
                date=day,
                total=total,
                completed=completed,
                stuck=stuck,
                area_sqft=area_sqft,
                result=dominant,
            )
        return summaries

    # ── v2.2.0 CR4 — timeline room-event extraction ───────────────────────────

    def _resolve_region_ids(
        self,
        rid_list: list[str],
        region_map: dict[str, str],
    ) -> list[str]:
        """Resolve region IDs to display names via region_map.

        Unknown IDs are returned as their raw ID string — data is never
        silently dropped. Name changes in the Smart Map are reflected
        automatically since region_map is passed at read time, not stored.
        """
        return [region_map.get(rid, rid) for rid in rid_list]

    @staticmethod
    def _extract_rid(item: Any) -> str:
        """Extract a region ID from a plan.upcoming entry.

        Handles two confirmed formats:
        - String (some firmware/app versions): "23"
        - Object (lewis 22.52.10+): {"type": "rid", "rid": "23"}
          Also accepts {"region_id": "23"} as a fallback.

        Returns an empty string when neither format is recognisable so the
        caller can filter it out.
        """
        if isinstance(item, dict):
            return str(item.get("rid") or item.get("region_id") or "")
        return str(item) if item is not None else ""

    def latest_cleaned_rooms(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> list[str] | None:
        """Return room names in cleaning-completion order from the most recent mission.

        CR4 — uses timeline.finEvents filtered to type='room' and status in (0, 6).
        status=0 = pass complete (normal).
        status=6 = pass complete after error recovery (lewis 22.52.10+ confirmed).
        status=1 = pass in progress — excluded.
        status=5 = interrupted by user/app — excluded.
        Each room appears once; the last qualifying event per rid is used.

        umf_regions: optional fallback for EPHEMERAL robots without coordinator.regions.
        When region_map is empty and umf_regions is provided, umf_regions is used.

        Returns None for whole-home missions (no 'room' events) or when
        the timeline field is absent (non-SMART robot or pre-merge record).
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        timeline = latest.get("timeline")
        if not isinstance(timeline, dict):
            return None
        fin_events = timeline.get("finEvents") or []
        seen: dict[str, int] = {}   # rid → index in ordered list
        ordered: list[str] = []
        for ev in fin_events:
            if ev.get("type") != "room":
                continue
            room = ev.get("room", {})
            if room.get("status") not in (0, 6):   # 0=complete, 6=complete-after-recovery
                continue
            rid = str(room.get("rid", ""))
            if not rid:
                continue
            if rid not in seen:
                seen[rid] = len(ordered)
                ordered.append(rid)
        if not ordered:
            return None
        return self._resolve_region_ids(ordered, effective_map)

    def latest_planned_order(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> list[str] | None:
        """Return room names in user-selected submission order.

        CR4 — uses timeline.plan.upcoming. Preserves the exact order the user
        selected rooms in the iRobot app. Returns None when absent or empty.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        timeline = latest.get("timeline")
        if not isinstance(timeline, dict):
            return None
        upcoming = timeline.get("plan", {}).get("upcoming")
        if not upcoming:
            return None
        rids = [self._extract_rid(r) for r in upcoming]
        rids = [r for r in rids if r]   # drop empty strings from unrecognised formats
        if not rids:
            return None
        return self._resolve_region_ids(rids, effective_map)

    def latest_mission_destination(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> str | None:
        """Return the last room in the planned order (final target of the job).

        Returns None for whole-home missions or when timeline is absent.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).
        """
        planned = self.latest_planned_order(region_map, umf_regions)
        return planned[-1] if planned else None

    def latest_room_coverage(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, float] | None:
        """Return per-room coverage fractions from the most recent mission.

        CR4 — uses room.totalArea / room.area from status=0 and status=6 events.
        totalArea = cumulative cleaned area across all passes (status=0/6 only).
        area = full room size (constant across events for the same rid).
        Values are clamped to [0.0, 1.0].

        Note: status=6 (completed after error recovery) events may not carry
        totalArea — such rooms are skipped from coverage but still appear in
        latest_cleaned_rooms(). This is expected behaviour for v2.2.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).

        Returns None when timeline is absent or no qualifying room events.
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        timeline = latest.get("timeline")
        if not isinstance(timeline, dict):
            return None
        fin_events = timeline.get("finEvents") or []
        coverage: dict[str, float] = {}
        for ev in fin_events:
            if ev.get("type") != "room":
                continue
            room = ev.get("room", {})
            if room.get("status") not in (0, 6):   # 0=complete, 6=complete-after-recovery
                continue
            rid = str(room.get("rid", ""))
            total_area = room.get("totalArea")
            area = room.get("area")
            if not rid or total_area is None or not area:
                continue
            try:
                fraction = min(1.0, max(0.0, float(total_area) / float(area)))
            except (ZeroDivisionError, TypeError, ValueError):
                continue
            coverage[rid] = fraction
        if not coverage:
            return None
        return {effective_map.get(rid, rid): frac for rid, frac in coverage.items()}

    def presence_windows(self, days: int) -> list[MissionWindow]:
        """Return gaps between missions as potential 'all-away' windows.

        Each window spans from the end of one mission to the start of the next.
        resulted_in_clean=True when a completed mission started within the window.
        Used by L6 analytics sensors.
        """
        records = self.query(days)
        if len(records) < 2:
            return []

        windows: list[MissionWindow] = []
        completed_starts: set[str] = {
            r["started_at"] for r in records
            if r.get("result") in ("completed", "stuck_and_resumed")
        }

        for i in range(len(records) - 1):
            prev_end_str = records[i].get("ended_at", "")
            next_start_str = records[i + 1].get("started_at", "")
            prev_end = dt_util.parse_datetime(prev_end_str)
            next_start = dt_util.parse_datetime(next_start_str)
            if prev_end is None or next_start is None:
                continue
            # Make timezone-aware if needed
            if prev_end.tzinfo is None:
                prev_end = prev_end.replace(tzinfo=timezone.utc)
            if next_start.tzinfo is None:
                next_start = next_start.replace(tzinfo=timezone.utc)
            if next_start <= prev_end:
                continue
            duration_min = int((next_start - prev_end).total_seconds() / 60)
            resulted = next_start_str in completed_starts
            windows.append(MissionWindow(
                started_at=prev_end,
                ended_at=next_start,
                duration_min=duration_min,
                resulted_in_clean=resulted,
            ))
        return windows

    def clean_streak(self) -> int:
        """Return consecutive days ending today with at least one completed mission."""
        today = dt_util.now().date()
        completed_dates: set[date] = set()
        for r in self._records:
            if r.get("result") in ("completed", "stuck_and_resumed"):
                dt = dt_util.parse_datetime(r.get("started_at", ""))
                if dt:
                    completed_dates.add(dt_util.as_local(dt).date())
        streak = 0
        day = today
        while day in completed_dates:
            streak += 1
            day -= timedelta(days=1)
        return streak

    def p75_area(self, days: int) -> float | None:
        """Return the 75th-percentile area_sqft across records in the last `days` days.

        F5f — self-calibrating home coverage baseline.  After 10+ missions this
        stabilises as a reliable proxy for a full-clean area, filtering out
        partial cleans (low end) and zero-area failures.

        Returns None when fewer than 5 positive-area records exist (insufficient
        history to establish a stable baseline). Threshold lowered from 10 to 5
        so the sensor activates within a week of first install.
        """
        areas = [
            r["area_sqft"]
            for r in self.query(days)
            if r.get("area_sqft") is not None and r["area_sqft"] > 0
        ]
        if len(areas) < 5:
            return None
        areas.sort()
        return areas[int(len(areas) * 0.75)]

    def wear_data(self, days: int) -> list[dict[str, Any]]:
        """Return daily bbrun.hr snapshots for the last `days` days.

        Returns one entry per calendar day — the highest recorded bbrun_hr
        value for that day — sorted ascending by date. Used by L4 wear
        intelligence to compute daily wear rates without needing consecutive-
        record arithmetic in the sensor layer.

        Returns an empty list when fewer than 2 days of data exist (not enough
        to compute a meaningful rate).
        """
        buckets: dict[date, int] = {}
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt and r.get("bbrun_hr") is not None:
                day = dt_util.as_local(dt).date()
                if day not in buckets or r["bbrun_hr"] > buckets[day]:
                    buckets[day] = r["bbrun_hr"]
        return sorted(
            [{"date": d.isoformat(), "bbrun_hr": hr} for d, hr in buckets.items()],
            key=lambda x: x["date"],
        )

    def wear_rate_since_reset(
        self,
        reset_hr: int,
        reset_at: str | None,
        current_hr: int,
    ) -> float | None:
        """Return average bbrun hours consumed per day since the last part reset.

        Returns None when:
        - reset_at is unknown (reset never recorded or store was empty)
        - current_hr has not advanced beyond reset_hr (robot not yet used)
        - fewer than 3 days have elapsed since reset (insufficient baseline)
        - reset_at cannot be parsed

        Never returns a negative value.
        """
        if reset_at is None or current_hr <= reset_hr:
            return None
        try:
            reset_dt = dt_util.parse_datetime(reset_at)
        except (ValueError, TypeError):
            return None
        if reset_dt is None:
            return None
        if reset_dt.tzinfo is None:
            reset_dt = reset_dt.replace(tzinfo=timezone.utc)
        days_elapsed = (dt_util.utcnow() - reset_dt).total_seconds() / 86400
        if days_elapsed < 3:
            return None
        rate = (current_hr - reset_hr) / days_elapsed
        return round(max(0.0, rate), 2)

    @staticmethod
    def _merge_cloud_fields(local: dict, cloud: dict) -> bool:
        """Copy missing analytics fields from a cloud record into a local record.

        Only copies when the local field is absent or None — never overwrites.
        Returns True if any field was written.
        """
        wrote = False
        for field in _CLOUD_MERGE_SCALAR:
            if local.get(field) is None and cloud.get(field) is not None:
                local[field] = cloud[field]
                wrote = True
        for field in _CLOUD_MERGE_ARRAY:
            if not local.get(field) and cloud.get(field):
                local[field] = cloud[field]
                wrote = True
        return wrote

    # ── L3 — Mission anomaly detection ────────────────────────────────────────

    def compute_rolling_stats(self, days: int = 30) -> dict | None:
        """Compute rolling mean/std for duration_min and area_sqft.

        L3 — Returns None when fewer than 20 missions are available (insufficient
        history to establish a stable baseline for anomaly detection).

        Returns a dict with keys:
          duration_mean, duration_std,
          area_mean, area_std,
          recharge_mean,
          dirt_p75            (75th-percentile dirt_events from cloud-merged records)
        """
        records = self.query(days)
        if len(records) < 20:
            return None

        durations = [r["duration_min"] for r in records if r.get("duration_min") is not None]
        areas = [r["area_sqft"] for r in records
                 if r.get("area_sqft") is not None and r["area_sqft"] > 0]
        recharges = [r["recharge_min"] for r in records
                     if r.get("recharge_min") is not None]
        dirts = [r["dirt"] for r in records if r.get("dirt") is not None]

        if len(durations) < 20:
            return None

        dur_mean = statistics.mean(durations)
        dur_std  = statistics.stdev(durations) if len(durations) > 1 else 0.0
        area_mean = statistics.mean(areas) if areas else None
        area_std  = statistics.stdev(areas) if len(areas) > 1 else 0.0
        rch_mean  = statistics.mean(recharges) if recharges else 0.0

        # 75th-percentile dirt events
        dirt_p75: float | None = None
        if dirts:
            dirts.sort()
            dirt_p75 = dirts[int(len(dirts) * 0.75)]

        return {
            "duration_mean": dur_mean,
            "duration_std":  dur_std,
            "area_mean":     area_mean,
            "area_std":      area_std,
            "recharge_mean": rch_mean,
            "dirt_p75":      dirt_p75,
        }

    def is_anomalous(
        self,
        record: dict,
        stats: dict,
        profile: Any = None,
    ) -> bool:
        """Return True when a record is statistically anomalous.

        L3 conditions (any one triggers):
          - duration > mean + 2×std AND area < mean_area − 1×std
            → robot spending more time covering less area (obstacle / brush issue)
          - recharge_min > learned_avg + 120 min
            → unusually long recharge mid-mission (battery degrading)
          - dirt > p75 × 2.5
            → extreme dirt event (spill, accident, pet)

        Pre-20-mission fallback (profile required):
          - area < profile.typical_coverage_sqft × SQFT_TO_M2 × 0.4

        Args:
            record: a single MissionStore record dict.
            stats:  output of compute_rolling_stats(); must not be None.
            profile: RobotProfile instance or None; only used for pre-20-mission check.
        """
        dur   = record.get("duration_min")
        area  = record.get("area_sqft")
        rch   = record.get("recharge_min")
        dirt  = record.get("dirt")

        # Condition 1 — struggling: slow AND low coverage
        if (
            dur is not None
            and stats["duration_std"] > 0
            and dur > stats["duration_mean"] + 2 * stats["duration_std"]
            and area is not None
            and stats["area_mean"] is not None
            and stats["area_std"] > 0
            and area < stats["area_mean"] - stats["area_std"]
        ):
            return True

        # Condition 2 — excessive recharge
        if rch is not None and rch > stats["recharge_mean"] + 120:
            return True

        # Condition 3 — extreme dirt spike
        if (
            dirt is not None
            and stats["dirt_p75"] is not None
            and stats["dirt_p75"] > 0
            and dirt > stats["dirt_p75"] * 2.5
        ):
            return True

        # Pre-20-mission fallback via robot profile.
        # Only engaged when no area statistics are available (stats["area_mean"]
        # is None), which happens when either:
        #   a) fewer than 20 missions exist in the window, OR
        #   b) no mission in the window has area_sqft data (600-series).
        # With a full statistical baseline (area_mean is not None), this check
        # is intentionally skipped to avoid flagging legitimate partial room
        # cleans (e.g. single-room scheduled clean) as anomalous.
        if profile is not None and area is not None and stats["area_mean"] is None:
            typical = getattr(profile, "typical_coverage_sqft", None)
            if typical is not None and typical > 0:
                typical_m2 = typical * SQFT_TO_M2
                if area * SQFT_TO_M2 < typical_m2 * 0.4:
                    return True

        return False

    @property
    def consecutive_anomalous(self) -> int:
        """Count of consecutive most-recent missions that are anomalous.

        L3 — evaluated lazily when accessed; always reads fresh from _records.
        Returns 0 when stats are unavailable (< 20 missions) or no anomalies.
        """
        stats = self.compute_rolling_stats()
        if stats is None:
            return 0
        count = 0
        for record in reversed(self._records):
            if self.is_anomalous(record, stats):
                count += 1
            else:
                break
        return count

    def backfill_from_cloud(
        self,
        cloud_records: list[dict],
        tolerance_sec: int = 120,
    ) -> BackfillResult:
        """Correct local MissionStore records using cloud /missionhistory timestamps.

        The 980/900-series firmware resets mssnStrtTm to 0 in the mission-end
        MQTT message. When callbacks.py cannot capture a valid start timestamp,
        started_at falls back to wall-clock at recording time, making
        duration_min ≈ 0 and the record id incorrect.

        Matches each local record against cloud records by end timestamp
        (±tolerance_sec), then corrects:
          - started_at  — from cloud startTime
          - ended_at    — from cloud timestamp
          - duration_min — recomputed from corrected timestamps
          - id          — regenerated from corrected started_at
          - area_sqft   — from cloud sqft when local value is None

        Analytics fields (dirt, chrgM, wlBars, etc.) are merged into every
        matched record regardless of whether a timestamp correction is needed.

        Matching uses ended_at (local) vs timestamp (cloud) because ended_at
        is always reliably recorded at wall-clock time.

        Args:
            cloud_records: raw cloud records, newest-first from API.
            tolerance_sec: max seconds between local ended_at and cloud
                           timestamp to count as the same mission. Default 120 s
                           covers MQTT delivery lag and clock skew.

        Returns:
            BackfillResult(corrected, enriched) — counts of timestamp
            corrections and analytics field merges respectively.
        """
        if not cloud_records or not self._records:
            return BackfillResult(corrected=0, enriched=0)

        # Build index of cloud records keyed by end timestamp for O(1) lookup.
        cloud_by_end: dict[int, dict] = {}
        for cr in cloud_records:
            ts = cr.get("timestamp")
            if ts is not None:
                cloud_by_end.setdefault(int(ts), cr)

        corrected = 0
        enriched = 0
        for local in self._records:
            ended_str = local.get("ended_at", "")
            if not ended_str:
                continue
            try:
                ended_dt = datetime.fromisoformat(ended_str)
            except (ValueError, TypeError):
                continue
            if ended_dt.tzinfo is None:
                ended_dt = ended_dt.replace(tzinfo=timezone.utc)
            local_end_ts = int(ended_dt.timestamp())

            # Find nearest cloud record within tolerance
            best_cr: dict | None = None
            best_delta = tolerance_sec + 1
            for cloud_ts, cr in cloud_by_end.items():
                delta = abs(cloud_ts - local_end_ts)
                if delta <= tolerance_sec and delta < best_delta:
                    best_delta = delta
                    best_cr = cr

            if best_cr is None:
                continue

            cloud_start = best_cr.get("startTime")
            cloud_end   = best_cr.get("timestamp")
            if not cloud_start or not cloud_end:
                continue

            new_started = datetime.fromtimestamp(
                int(cloud_start), tz=timezone.utc
            )
            new_ended = datetime.fromtimestamp(
                int(cloud_end), tz=timezone.utc
            )

            # Only correct if timestamps differ meaningfully (>5 min)
            old_started_str = local.get("started_at", "")
            try:
                old_started = datetime.fromisoformat(old_started_str)
                if old_started.tzinfo is None:
                    old_started = old_started.replace(tzinfo=timezone.utc)
                delta_start = abs((new_started - old_started).total_seconds())
            except (ValueError, TypeError):
                delta_start = float("inf")

            # Always merge analytics fields regardless of timestamp delta.
            merge_wrote = self._merge_cloud_fields(local, best_cr)
            if merge_wrote:
                enriched += 1

            # Only correct timestamps when they differ meaningfully (> 5 min).
            if delta_start < 300:
                continue

            new_duration = max(0, round(
                (new_ended - new_started).total_seconds() / 60
            ))
            new_id = f"m_{int(new_started.timestamp())}"

            local["started_at"]   = new_started.isoformat()
            local["ended_at"]     = new_ended.isoformat()
            local["duration_min"] = new_duration
            local["id"]           = new_id

            # area_sqft is the canonical local name; backfill only when absent.
            if local.get("area_sqft") is None and best_cr.get("sqft") is not None:
                local["area_sqft"] = best_cr["sqft"]

            corrected += 1
            _LOGGER.debug(
                "MissionStore backfill: corrected %s → started_at=%s "
                "duration=%dmin (was %s, delta=%.0fs)",
                new_id, new_started.isoformat(),
                new_duration, old_started_str, delta_start,
            )

        if corrected or enriched:
            _LOGGER.info(
                "MissionStore backfill: corrected=%d timestamp(s), enriched=%d record(s)",
                corrected, enriched,
            )
        return BackfillResult(corrected=corrected, enriched=enriched)

    def merge_latest_from_cloud(
        self,
        cloud_records: list[dict],
        tolerance_sec: int = 120,
    ) -> bool:
        """Merge cloud analytics fields into the most recent local record.

        Called after the post-mission cloud refresh (F4b). Targets only
        the last record — the mission that just ended is newest in both stores.
        Uses the same ±tolerance_sec end-timestamp matching as backfill_from_cloud.

        Returns True if any field was written to the record.
        """
        if not self._records or not cloud_records:
            return False

        local = self._records[-1]
        ended_str = local.get("ended_at", "")
        if not ended_str:
            return False

        try:
            ended_dt = datetime.fromisoformat(ended_str)
        except (ValueError, TypeError):
            return False

        if ended_dt.tzinfo is None:
            ended_dt = ended_dt.replace(tzinfo=timezone.utc)

        local_end_ts = int(ended_dt.timestamp())

        best_cr: dict | None = None
        best_delta = tolerance_sec + 1
        for cr in cloud_records:
            ts = cr.get("timestamp")
            if ts is None:
                continue
            delta = abs(int(ts) - local_end_ts)
            if delta <= tolerance_sec and delta < best_delta:
                best_delta = delta
                best_cr = cr

        if best_cr is None:
            return False

        return self._merge_cloud_fields(local, best_cr)

    async def async_backfill_statistics(
        self,
        hass: HomeAssistant,
        entry_id: str,
        robot_name: str,
    ) -> None:
        """Inject historical mission data into HA Long-Term Statistics.

        F7j -- backfills three external statistic series from MissionStore records,
        making a full year of history immediately available in the HA Statistics
        graph card.  async_add_external_statistics() is idempotent -- duplicate
        start timestamps are silently ignored, so this is safe to call on every
        startup and after every new record.

        Series:
          roomba_plus:{entry_id}_area_cleaned_m2    -- daily sum (m², has_sum)
          roomba_plus:{entry_id}_mission_duration_min -- daily sum (min, has_sum)
          roomba_plus:{entry_id}_missions_completed  -- daily count (missions, has_sum)

        Gate: area series requires cloud records with area_sqft.  Duration and
        completion count work for all robots from local records.
        """
        try:
            from homeassistant.components.recorder.statistics import (
                async_add_external_statistics,
            )
            from homeassistant.components.recorder.models import (
                StatisticData,
                StatisticMetaData,
            )
            # mean_type required from HA 2026.11 — pass as integer (0 = NONE)
            # to avoid import dependency on StatisticsMeanType which may not
            # exist in older HA versions. StatisticMetaData is a TypedDict so
            # it accepts any value without type checking.
            _mean_type_none = 0
        except ImportError:
            _LOGGER.debug(
                "MissionStore: recorder not available -- skipping statistics backfill"
            )
            return

        import inspect as _inspect

        async def _import_stats(meta, stats):
            """Call async_add_external_statistics, handling both sync and async variants."""
            result = async_add_external_statistics(hass, meta, stats)
            if _inspect.isawaitable(result):
                await result

        def _make_meta(name, statistic_id, unit):
            return StatisticMetaData(
                has_mean=False,
                has_sum=True,
                mean_type=_mean_type_none,  # 0 = NONE (no mean), required from HA 2026.11
                name=name,
                source=source,
                statistic_id=statistic_id,
                unit_class=None,            # required from HA 2025.11 — None = no unit conversion
                unit_of_measurement=unit,
            )

        if not self._records:
            return

        # Group records by hour-truncated start timestamp (LTS granularity)
        area_stats: list[StatisticData] = []
        duration_stats: list[StatisticData] = []
        completion_stats: list[StatisticData] = []

        for r in self._records:
            started_str = r.get("started_at", "")
            if not started_str:
                continue
            try:
                started_dt = dt_util.parse_datetime(started_str)
                if started_dt is None:
                    continue
                if started_dt.tzinfo is None:
                    started_dt = started_dt.replace(tzinfo=timezone.utc)
                # Truncate to hour for LTS
                bucket = started_dt.replace(minute=0, second=0, microsecond=0)
            except (ValueError, TypeError):
                continue

            area_sqft = r.get("area_sqft")
            duration_min = r.get("duration_min") or 0
            is_completed = r.get("result") in ("completed", "stuck_and_resumed")

            if area_sqft is not None:
                area_m2 = round(float(area_sqft) * SQFT_TO_M2, 2)
                area_stats.append(StatisticData(start=bucket, sum=area_m2))

            duration_stats.append(StatisticData(start=bucket, sum=float(duration_min)))
            completion_stats.append(StatisticData(start=bucket, sum=1.0 if is_completed else 0.0))

        source = "roomba_plus"

        # HA validates statistic_id strictly: domain:object_id where object_id
        # must be lowercase letters, digits and underscores only.
        # Entry IDs are ULIDs (uppercase) — convert to lowercase.
        safe_entry_id = entry_id.lower()

        if area_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Area cleaned", f"{source}:{safe_entry_id}_area_cleaned_m2", "m\u00b2"),
                area_stats,
            )

        if duration_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Mission duration", f"{source}:{safe_entry_id}_mission_duration_min", "min"),
                duration_stats,
            )

        if completion_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Missions completed", f"{source}:{safe_entry_id}_missions_completed", "missions"),
                completion_stats,
            )

        _LOGGER.debug(
            "MissionStore: statistics backfill complete for %s "
            "(%d area, %d duration, %d completion points)",
            entry_id,
            len(area_stats),
            len(duration_stats),
            len(completion_stats),
        )
