"""MissionTimerStore — persists mission run-time across HA restarts.

MP1 (v2.6.0) — a purely transient counter is lost on HA restart mid-mission,
producing misleading 0 % progress. This store persists the current mission_id
and accumulated run_sec to hass.storage so the progress sensor can resume
from the correct value after a restart.

Only the current active mission is stored. The store is cleared when a new
mission_id is detected (i.e. robot starts a new mission).

Lifecycle:
  - Instantiated in async_setup_entry for SMART + cloud robots.
  - Call async_load() on setup to resume any in-progress mission.
  - Call update() on every phase=="run" MQTT message to accumulate.
  - Call clear() when mission_id changes or mission ends.
  - async_save() is called automatically by update() and clear().

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import asyncio
import time
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

_LOGGER = logging.getLogger(__name__)

STORAGE_VERSION = 1
_STORAGE_KEY_PREFIX = "roomba_plus_mission_timer"


class MissionTimerStore:
    """Persist elapsed run-only seconds for the active mission.

    Fields stored:
        mission_id: str | None   — current mission identifier (blid + start_ts)
        run_sec: int             — accumulated run-only seconds
        last_phase_ts: float     — monotonic timestamp of last phase=="run" entry;
                                   used to compute delta on next update()
    """

    def __init__(self) -> None:
        self.mission_id: str | None = None
        self.run_sec: int = 0
        self._last_phase_ts: float = 0.0

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted timer from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            return
        try:
            self.mission_id = data.get("mission_id")
            self.run_sec = int(data.get("run_sec", 0))
            _LOGGER.debug(
                "MissionTimerStore: resumed mission=%s run_sec=%d",
                self.mission_id, self.run_sec,
            )
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionTimerStore: load failed — %s", exc)

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current timer state."""
        store = Store(hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({
            "mission_id": self.mission_id,
            "run_sec": self.run_sec,
        })

    # ── Public API ────────────────────────────────────────────────────────────

    def on_phase_run(self, mission_id: str, hass: HomeAssistant, entry_id: str) -> None:
        """Called each time phase=="run" is observed in MQTT.

        Accumulates elapsed wall-clock delta since the previous phase=="run"
        message. Ignores inter-message gaps > 120 s (e.g. recharges, pauses,
        HA restarts) to avoid double-counting non-cleaning time.

        Saves asynchronously via asyncio.run_coroutine_threadsafe (thread-safe;
        called from paho-MQTT thread via callbacks.py) to avoid blocking
        the MQTT callback loop.
        """
        now = time.monotonic()
        if self.mission_id != mission_id:
            # New mission — reset counter
            self.mission_id = mission_id
            self.run_sec = 0
            self._last_phase_ts = now
            asyncio.run_coroutine_threadsafe(
                self.async_save(hass, entry_id),
                hass.loop,
                )
            return

        if self._last_phase_ts > 0:
            delta = now - self._last_phase_ts
            # Clamp: ignore gaps > 120 s (recharge, pause, restart)
            if 0 < delta < 120:
                self.run_sec += int(delta)
                asyncio.run_coroutine_threadsafe(
                    self.async_save(hass, entry_id),
                    hass.loop,
                    )
        self._last_phase_ts = now

    def on_phase_other(self) -> None:
        """Called when phase is not "run" — resets the phase timestamp."""
        self._last_phase_ts = 0.0

    def clear(self, hass: HomeAssistant, entry_id: str) -> None:
        """Reset the timer at mission end. Saves asynchronously."""
        self.mission_id = None
        self.run_sec = 0
        self._last_phase_ts = 0.0
        asyncio.run_coroutine_threadsafe(
            self.async_save(hass, entry_id),
            hass.loop,
            )
