"""Data models for the Roomba+ integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

from homeassistant.config_entries import ConfigEntry

if TYPE_CHECKING:
    from roombapy import Roomba
    from .blocking_manager import BlockingManager
    from .cloud_coordinator import IrobotCloudCoordinator
    from .const import RobotProfile
    from .geometry_store import GeometryStore
    from .grid_store import GridStore                # v2.2.0 F9
    from .room_seg_store import RoomSegStore          # ROOM-SEG
    from .umf_aligner import UmfAligner              # v2.3.0 F8
    from .maintenance_store import MaintenanceStore
    from .mission_store import MissionStore          # v1.8.0 L1
    from .map_renderer import MapRenderer
    from .presence_manager import PresenceManager    # v1.8.0 L6
    from .dirt_threshold_manager import DirtThresholdManager  # v2.4 F11
    from .outline_store import OutlineStore                    # v2.4 F-EPHEMERAL
    from .robot_profile_store import RobotProfileStore        # v2.6 L4
    from .mission_timer_store import MissionTimerStore        # v2.6 MP1


class MapCapability(Enum):
    """Map rendering capability level of a robot.

    NONE:      600-series bump-and-run — no pose data, no map.
    EPHEMERAL: 900-series VSLAM — pose data available, map is per-mission only,
               no persistent pmaps. RoomSegStore accumulates rooms/doors
               across missions (watershed segmentation on GridStore).
    SMART:     i/s/j/m-series — pose data + persistent pmaps/regions.
               Cloud coordinator is created when credentials are available.
    """

    NONE = "none"
    EPHEMERAL = "ephemeral"
    SMART = "smart"


@dataclass
class RoombaData:
    """Runtime data stored in config_entry.runtime_data."""

    roomba: Roomba
    blid: str
    map_capability: MapCapability = MapCapability.NONE
    renderer: MapRenderer | None = None
    geometry_store: GeometryStore | None = None
    maintenance_store: MaintenanceStore | None = None
    # Optional cloud coordinator — None when no credentials or non-SMART robot
    cloud_coordinator: IrobotCloudCoordinator | None = None
    # Optional blocking manager — None when CONF_BLOCKING_SENSORS not configured
    blocking_manager: BlockingManager | None = None  # v1.7.0 L5
    # v1.8.0 — Mission log, presence scheduling, and error state
    mission_store: MissionStore | None = None
    presence_manager: PresenceManager | None = None
    last_error_code: int | None = None      # persisted via MissionStore on load
    last_error_at: str | None = None        # ISO datetime string
    last_error_zone: str | None = None      # zone name at last error time

    # F6a/F6b — consecutive-update counters for performance & battery issues.
    # Stored here (not in MaintenanceStore) because they reset on every HA
    # restart — they measure run-time sensor trend, not persistent history.
    consecutive_declining_speed: int = 0
    consecutive_battery_warn: int = 0

    # F6a/F6b — latest sensor values cached so repair check functions can
    # read them without importing sensor.py (avoids circular imports).
    cleaning_speed_trend_value: str | None = None   # "improving"|"stable"|"declining"|"unknown"
    dirt_density_rising: bool = False
    recharge_fraction_value: float | None = None
    battery_retention_value: float | None = None

    # F6f — battery contact/bus-communication anomaly detection. A real
    # contact problem can both (a) cause an implausible instantaneous
    # jump in batPct (the BMS link drops and recovers, not the chemistry
    # changing) and (b) manifest as the per-charge-cycle peak declining
    # over successive cycles (intermittent contact reduces effective
    # charge transferred each cycle). Both feed the same repair issue —
    # see repairs.py::async_check_battery_contact_issue.
    last_batpct_value: float | None = None
    last_batpct_at: float | None = None   # time.monotonic() of last_batpct_value
    consecutive_battery_contact_anomaly: int = 0
    current_charge_cycle_peak: float | None = None
    charge_cycle_peaks: list = field(default_factory=list)   # bounded, most-recent-last
    was_charging: bool = False   # edge-detect charge-cycle start/end

    # v2.2.0 — GridStore for occupancy heatmap and stuck-cell analysis (F9)
    grid_store: GridStore | None = None
    room_seg_store: RoomSegStore | None = None
    # v2.3.0 — UMF spatial fusion aligner (SMART + EPHEMERAL when Q7 confirmed)
    umf_aligner: UmfAligner | None = None
    # v2.4.0 — Demand-based cleaning trigger (F11, SMART + cloud only)
    dirt_threshold_manager: "DirtThresholdManager | None" = None
    # v2.4.0 — Room outline accumulator (F-EPHEMERAL, 900-series only)
    outline_store: "OutlineStore | None" = None
    # v2.5.0 — Manufacturer reference profile for self-calibrating features (RF0)
    robot_profile: "RobotProfile | None" = None
    # v2.6.0 — Centralised learned state store (L4)
    robot_profile_store: "RobotProfileStore | None" = None
    # v2.6.0 MS1 — Timestamp set when DirtThresholdManager fires a start command.
    # callbacks.py checks this within 30 s to stamp initiator="demand" on the record.
    demand_triggered_ts: float | None = None
    # v2.6.0 MP1 — Persistent mission run-timer (SMART + cloud only)
    mission_timer_store: "MissionTimerStore | None" = None
    # v2.8.0 ARC1 — CloudMissionArchive (cloud + any map_capability)
    mission_archive: "MissionArchive | None" = None
    # v2.2.0 — user-assigned floor name for household REST endpoint (F10a)
    floor_label: str = ""

    # v2.8.3 — MQTT-watchdog: wall-clock timestamp of the last received MQTT
    # message.  Written by the paho-MQTT thread in callbacks.py; read by the
    # RoombaMqttStale binary sensor on its 60-second tick.  Python's GIL makes
    # float reads/writes atomic so no explicit locking is needed.
    # 0.0 = no message received yet (watchdog must not fire until first message).
    last_mqtt_message_ts: float = 0.0

    # v2.8.3 — FW-SENSOR: firmware version tracking.
    # last_firmware_version: most recent non-None softwareVer seen from MQTT.
    # firmware_updated_at: wall-clock timestamp when softwareVer last changed
    #   (None until a change is detected; stays set for 24 h to keep the
    #   firmware_updated binary sensor ON).
    last_firmware_version: str | None = None
    firmware_updated_at: float | None = None

    def roomba_reported_state(self) -> dict[str, Any]:
        """Return the reported state dict from master_state.

        ``or {}`` coerces an explicit null (``{"state": null}``) from a sparse
        MQTT frame to an empty dict; a dict default would only guard a missing
        key, not a present-but-null value.
        """
        return (self.roomba.master_state.get("state") or {}).get("reported") or {}

    @property
    def has_cloud(self) -> bool:
        """True when the cloud coordinator is active and has fetched data."""
        return (
            self.cloud_coordinator is not None
            and self.cloud_coordinator.data is not None
        )


# Typed config entry — gives full IDE type safety throughout the integration
type RoombaConfigEntry = ConfigEntry[RoombaData]
