"""Presence-Aware Scheduling Manager for Roomba+.

Controls schedHold based on tracked person entity states. When all tracked
persons leave home, starts a configurable delay then unfreezes the cleaning
schedule (schedHold=False). When anyone returns, re-freezes it (schedHold=True).

The manager writes schedHold only when it is the one that unfroze it, tracked
via the is_managed_hold property. This prevents it from interfering with
manual schedule hold toggles.

Lifecycle (must be respected by callers):
  - Instantiate in async_setup_entry when presence_scheduling_enabled=True.
  - Call start() AFTER config_entry.runtime_data is set.
  - Store in entry.runtime_data.presence_manager.
  - Call cancel() in async_unload_entry — always.
  - Full HA reload is triggered on options change (no in-place restart needed).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from collections import defaultdict
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Any

from homeassistant.core import HomeAssistant, callback
from homeassistant.util import dt as dt_util

from .const import (
    CLEANING_PHASES,
    CONF_AWAY_DELAY_MIN,
    CONF_CLEAN_DELAY_MIN,
    CONF_PRESENCE_ENTITIES,
    CONF_PRESENCE_MODE,
    DEFAULT_AWAY_DELAY_MIN,
    DEFAULT_CLEAN_DELAY_MIN,
    DEFAULT_PRESENCE_MODE,
    EVENT_ALL_AWAY,
    EVENT_PERSON_DETECTED_DURING_CLEAN,
)

if TYPE_CHECKING:
    from .models import RoombaConfigEntry

_LOGGER = logging.getLogger(__name__)

# States that count as "home" — everything else is treated as "away"
_HOME_STATES = frozenset({"home", "on", "true"})
# States where the person entity is unreliable — treat as "might be home" (safe default)
_PRESENCE_UNUSABLE = frozenset({"unavailable", "unknown"})
# Mission phases that indicate an active clean in progress.
#
# IMPORTED, not repeated: const.py owns this set and carries the reason
# `evac` is in it. Two copies drifting apart would mean presence logic
# and mission logic disagreeing about whether the robot is cleaning.
_ACTIVE_CLEANING_PHASES = CLEANING_PHASES


def _event_dt(item: datetime | tuple[datetime, bool]) -> datetime:
    """Return the datetime from a _clean_events entry.

    Handles both the v2.5.0 format (plain datetime) and the v2.6.0 format
    ((datetime, was_all_away) tuple). Backward-compat for pre-existing data
    seeded by tests or migrated from storage.
    """
    # Both stored shapes yield a datetime -- v2.5.0 wrote one
    # directly, v2.6.0 writes `(datetime, was_all_away)`.
    return item[0] if isinstance(item, tuple) else item


class PresenceManager:
    """Manage schedHold based on tracked person entity states."""

    def __init__(self, hass: HomeAssistant, config_entry: RoombaConfigEntry) -> None:
        self._hass = hass
        self._entry = config_entry
        self._cancel_listeners: list[Any] = []
        self._away_task: asyncio.Task[None] | None = None
        # True when THIS manager set schedHold=False (unfreeze).
        # Used by is_managed_hold so the binary sensor can distinguish
        # presence-managed holds from manual ScheduleHoldSwitch toggles.
        self._managed_hold: bool = False
        self._did_unfreeze: bool = False  # True only when PM actually performed the unfreeze
        # R1: initialised here so record_clean_event/presence_windows never need hasattr
        #: Both formats, which `_event_dt` above already handles.
        #:
        #: v2.5.0 stored a plain datetime and v2.6.0 stores
        #: `(datetime, was_all_away)`. The reader was written for both
        #: on purpose -- seeded or migrated data can still be in the old
        #: shape -- and this declaration only ever named the old one.
        self._clean_events: dict[
            tuple[int, int], list[datetime | tuple[datetime, bool]]
        ] = defaultdict(list)

    # ── Setup ─────────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Register state listeners and evaluate presence immediately.

        Must be called AFTER config_entry.runtime_data is set so the manager
        can read roomba state.
        """
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        if not person_ids:
            _LOGGER.warning(
                "PresenceManager: no presence entities configured — inactive"
            )
            return

        @callback
        def _on_state_changed(event: Any) -> None:
            if event.data.get("entity_id") in person_ids:
                self._hass.async_create_task(
                    self._evaluate_presence(),
                    name="roomba_plus_presence_eval",
                )

        unsub = self._hass.bus.async_listen("state_changed", _on_state_changed)
        self._cancel_listeners.append(unsub)

        # Evaluate on setup so initial state is applied immediately
        self._hass.async_create_task(self._evaluate_presence())
        _LOGGER.debug(
            "PresenceManager: started, tracking %s", person_ids
        )

    # ── Core logic ────────────────────────────────────────────────────────────

    async def _evaluate_presence(self) -> None:
        """Check all tracked persons and act on the result."""
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        if not person_ids:
            return  # safety guard: no entities configured
        all_away = all(
            (st := self._hass.states.get(eid)) is not None
            and st.state not in _PRESENCE_UNUSABLE  # unusable → treat as "might be home"
            and st.state not in _HOME_STATES
            for eid in person_ids
        )
        if all_away:
            await self._handle_all_away()
        else:
            await self._handle_someone_home()

    async def _handle_all_away(self) -> None:
        """All persons away — start delay before unfreezing schedule."""
        if self._away_task is not None and not self._away_task.done():
            return  # delay already running

        delay_min: int = self._entry.options.get(
            CONF_AWAY_DELAY_MIN, DEFAULT_AWAY_DELAY_MIN
        )
        _LOGGER.debug(
            "PresenceManager: all away — %d min delay started", delay_min
        )
        self._away_task = self._hass.async_create_task(
            self._away_delay(delay_min * 60),
            name="roomba_plus_away_delay",
        )

    async def _away_delay(self, seconds: int) -> None:
        """Wait then unfreeze schedule or fire event depending on mode."""
        try:
            await asyncio.sleep(seconds)
        except asyncio.CancelledError:
            return

        # THE SECOND DELAY, which existed as an option and was never
        # read. The two answer different questions: the away delay waits
        # to be sure everyone has really gone -- somebody walking to the
        # postbox should not start a mission -- and this one waits before
        # cleaning, because a car still on the drive is not a reason to
        # send the robot out.
        #
        # Somebody who set both got only the first, and the dialog said
        # nothing about it.
        clean_delay: int = self._entry.options.get(
            CONF_CLEAN_DELAY_MIN, DEFAULT_CLEAN_DELAY_MIN
        )
        if clean_delay > 0:
            _LOGGER.debug(
                "PresenceManager: away confirmed, %d min before cleaning",
                clean_delay,
            )
            try:
                await asyncio.sleep(clean_delay * 60)
            except asyncio.CancelledError:
                # An arrival during this window cancels the whole task,
                # and cleaning must not start after it.
                return

        mode = self._entry.options.get(CONF_PRESENCE_MODE, DEFAULT_PRESENCE_MODE)
        if mode == "away_only":
            await self._set_schedules_paused(False)
            self._managed_hold = False
            self._did_unfreeze = True  # remember we performed the unfreeze
        else:
            # always_ask: fire event and let user automation handle it
            self._hass.bus.async_fire(EVENT_ALL_AWAY, {})
        self._away_task = None
        #: Which schedules WE switched off, so a resume does not enable
        #: one the user had turned off themselves.
        self._paused_schedule_ids: set[str] = set()

    async def _handle_someone_home(self) -> None:
        """A person arrived — cancel delay and re-freeze if WE unfroze it."""
        if self._away_task and not self._away_task.done():
            self._away_task.cancel()
            self._away_task = None
            _LOGGER.debug("PresenceManager: arrival cancelled away delay")
            return

        data = self._entry.runtime_data

        # PRIME HAS NO LOCAL ROBOT TO READ, and this reached past that.
        #
        # `_set_schedules_paused` branches on `prime_robot` correctly and
        # never touches `data.roomba` on a Prime entry. This function did
        # not: it read `data.roomba.master_state` to decide whether to
        # re-freeze, before the branch that would have protected it.
        #
        # `data.roomba` is None on every CLOUD_ONLY entry by design, so a
        # Prime user who switched on presence scheduling got an
        # AttributeError the first time somebody came home. Nothing
        # caught it -- no test builds a Prime entry with presence
        # enabled, and the field question about presence on Prime has
        # been open in the tester notes for a week with no answer.
        #
        # Found by mypy, not by a report.
        #
        # On Prime the decision is made from the schedules themselves:
        # `_did_unfreeze` records that WE paused them, which is the same
        # ownership check `schedHold` provides on Classic, without a
        # shadow field to read.
        if data.roomba is None:
            if self._did_unfreeze:
                await self._set_schedules_paused(True)
                self._managed_hold = True
                self._did_unfreeze = False
            return

        state = data.roomba.master_state.get("state", {}).get("reported", {})

        if "schedHold" not in state:
            _LOGGER.debug(
                "PresenceManager: schedHold not in state — cannot write"
            )
            return

        # Only re-freeze if WE previously performed the unfreeze.
        # _did_unfreeze is set True only when _away_delay calls _set_sched_hold(False).
        # This prevents the PM from claiming ownership of a manual hold.
        if not state.get("schedHold", False) and self._did_unfreeze:
            await self._set_schedules_paused(True)
            self._managed_hold = True
            self._did_unfreeze = False

            # Fire event if a clean is actively running
            phase = (state.get("cleanMissionStatus") or {}).get("phase", "")
            if phase in _ACTIVE_CLEANING_PHASES:
                self._hass.bus.async_fire(EVENT_PERSON_DETECTED_DURING_CLEAN, {})

    async def _set_schedules_paused(self, paused: bool) -> None:
        """Pauses or resumes the robot's schedules, either generation.

        CLASSIC HAS A FIELD FOR THIS AND PRIME DOES NOT. `schedHold` is
        Classic's way of holding a schedule without changing it -- the
        entry stays visible in the app and simply does not run.

        A Prime robot carries `schedHold` in its shadow, accepts a write
        to it, reads it back changed, **and runs anyway**. APK research
        10 explains why: the field appears once in the Prime app, with no
        serialisation annotation and no consumer across 3801 classes. It
        is inherited plumbing, not a control.

        What Prime offers instead is `enabled` per schedule, which the
        app itself uses. So this disables and re-enables them.

        **ONE VISIBLE DIFFERENCE, and it is worth knowing:** a paused
        Classic schedule still looks scheduled in the iRobot app; a
        paused Prime one looks switched off. Somebody checking the app
        while the house is empty will see their schedules off. That is
        honest -- they are -- but it is not what Classic does.
        """
        data = self._entry.runtime_data
        if getattr(data, "prime_robot", None) is None:
            await self._set_sched_hold(paused)
            return

        # LATE ON PURPOSE: prime_schedule_switch imports back into the
        # presence chain, so a module-level import here is a real cycle.
        from .prime_schedule_switch import (  # noqa: PLC0415
            async_read_schedule_containers,
        )

        containers = await async_read_schedule_containers(self._entry)
        if not containers:
            return

        # ONLY SCHEDULES WE PAUSED GET RESUMED. Turning everything back
        # on would enable a schedule the user had deliberately switched
        # off before leaving -- the robot would then run on a day they
        # had opted out of, and nothing in Home Assistant would explain
        # why.
        for container_id, schedules in containers:
            changed = False
            for schedule in schedules or []:
                options = getattr(schedule, "options", None)
                if options is None or getattr(options, "deleted", None):
                    continue
                sid = getattr(schedule, "schedule_id", None)
                if paused:
                    if getattr(options, "enabled", None) is not True:
                        continue
                    if sid is not None:
                        self._paused_schedule_ids.add(sid)
                    options.enabled = False
                    changed = True
                elif sid in self._paused_schedule_ids:
                    options.enabled = True
                    self._paused_schedule_ids.discard(sid)
                    changed = True
            if changed:
                assert data.prime_robot is not None  # noqa: S101 - branched above
                await data.prime_robot.update_schedules(
                    data.prime_household_id, container_id, schedules
                )

    async def _set_sched_hold(self, value: bool) -> None:
        """Write schedHold preference to the robot.

        Guards against robots that don't support schedHold.
        Uses async_add_executor_job because roombapy's set_preference is
        synchronous (MQTT publish).
        """
        data = self._entry.runtime_data

        # CLASSIC ONLY. `_set_schedules_paused` branches on
        # `prime_robot` and calls this in the else -- Prime disables the
        # schedules themselves instead, because a Prime robot accepts a
        # write to `schedHold`, reads it back changed, and runs anyway.
        #
        # The sibling that reaches this from the arrival side had the
        # same shape and no such branch, which is how a Prime user got
        # an AttributeError the first time somebody came home. That one
        # is fixed; this states the invariant for the path that was
        # always correct.
        roomba = data.roomba
        if roomba is None:
            _LOGGER.debug(
                "PresenceManager: schedHold is a Classic field and there "
                "is no local robot -- schedules are paused directly"
            )
            return

        state = roomba.master_state.get("state", {}).get("reported", {})
        if "schedHold" not in state:
            _LOGGER.warning(
                "PresenceManager: schedHold not in robot state — cannot write"
            )
            return
        await self._hass.async_add_executor_job(
            roomba.set_preference, "schedHold", value
        )
        _LOGGER.info("PresenceManager: schedHold set to %s", value)

    # ── Public API ────────────────────────────────────────────────────────────

    # ── Presence windows (F12a) ────────────────────────────────────────────

    def record_clean_event(self, started_at: datetime) -> None:
        """Record that a clean started at the given UTC datetime.

        F12a — called from callbacks.py at mission start so the manager
        can build a day×hour reliability matrix.
        Stores (weekday, hour) → list[(datetime, was_all_away)] in _clean_events.

        ALG1 (v2.6.0): snapshots presence state at the moment of recording so
        the reliability score genuinely measures "fraction of cleans where everyone
        was away", not just recency of historical cleans.

        P5: prunes events older than 90 days only when total > 500 events;
        for typical use (≤180 events over 90 days) the check is O(1).
        """
        # P5: only prune when the total event count exceeds the threshold
        total = sum(len(v) for v in self._clean_events.values())
        if total > 500:
            cutoff = dt_util.utcnow() - timedelta(days=90)
            for key in list(self._clean_events):
                self._clean_events[key] = [
                    item for item in self._clean_events[key]
                    if _event_dt(item) > cutoff
                ]
        # Bug A fix: use dt_util.as_local() so the slot weekday and hour match
        # HA's configured timezone, not the server OS timezone. This must agree
        # with preferred_window() which uses dt_util.now().weekday().
        local_dt = dt_util.as_local(started_at)
        slot = (local_dt.weekday(), local_dt.hour)

        # ALG1: snapshot whether all tracked persons are currently away.
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        was_all_away = (
            bool(person_ids)
            and all(
                (st := self._hass.states.get(eid)) is not None
                and st.state not in _PRESENCE_UNUSABLE
                and st.state not in _HOME_STATES
                for eid in person_ids
            )
        )
        self._clean_events[slot].append((started_at, was_all_away))
        _LOGGER.debug(
            "PresenceManager: recorded clean at weekday=%d hour=%d away=%s",
            *slot, was_all_away,
        )

    def presence_windows(self) -> dict[tuple[int, int], float]:
        """Return the away-reliability matrix for cleaning windows.

        F12a — Returns a dict mapping (weekday, hour) → reliability score (0.0–1.0).
          weekday: 0=Monday … 6=Sunday
          hour: 0–23 local time
          reliability: fraction of cleans in this slot where all persons were away.

        ALG1 (v2.6.0): score is now away_cleans / total_cleans per slot,
        measuring genuine "away during clean" rather than recency weighting.
        Slots with fewer than 3 recent observations are excluded to avoid
        a single lucky away-clean giving a false high reliability.

        Empty when fewer than 5 clean events recorded (insufficient history).
        """
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        if not person_ids:
            return {}

        total_events = sum(len(v) for v in self._clean_events.values())
        if total_events < 5:
            return {}

        now = dt_util.utcnow()
        result: dict[tuple[int, int], float] = {}
        for slot, events in self._clean_events.items():
            if not events:
                continue
            # Consider only the last 30 days for scoring
            recent = [
                item for item in events
                if (now - _event_dt(item)).days <= 30
            ]
            if len(recent) < 3:
                # Insufficient recent history for this slot
                continue
            away_count = sum(1 for item in recent if isinstance(item, tuple) and item[1])
            result[slot] = away_count / len(recent)
        return result

    def preferred_window(self) -> tuple[int, int] | None:
        """Return the (weekday, hour) slot with the highest reliability for today.

        F12a — Filters to slots matching today's weekday, then returns the
        hour with the highest score. Returns None when no history is available
        or all scores are zero.

        R2: uses dt_util.now() so today's weekday is derived from HA's configured
        timezone, not the server OS timezone. Affects users whose HA server runs
        in UTC while their location is not UTC (midnight crossovers would return
        the wrong day with datetime.now()).
        """
        windows = self.presence_windows()
        if not windows:
            return None
        today = dt_util.now().weekday()   # R2: HA timezone, not server timezone
        today_slots = {
            (wd, hr): score
            for (wd, hr), score in windows.items()
            if wd == today and score > 0
        }
        if not today_slots:
            return None
        return max(today_slots, key=today_slots.__getitem__)

    @property
    def window_is_today(self) -> bool:
        """True when the best cleaning window falls on today's weekday.

        ALG2 (v2.6.0) — exposed as extra_state_attributes on the
        optimal_clean_window sensor so cards and automations can distinguish
        "clean now (today)" from "clean tomorrow at this time".
        """
        slot = self.preferred_window()
        if slot is None:
            return False
        return slot[0] == dt_util.now().weekday()

    @property
    def is_managed_hold(self) -> bool:
        """True when this manager is the source of the current schedHold=True."""
        return self._managed_hold

    def cancel(self) -> None:
        """Cancel all listeners and tasks. Idempotent — safe to call multiple times."""
        for unsub in self._cancel_listeners:
            try:
                unsub()
            except Exception:  # noqa: BLE001
                pass
        self._cancel_listeners.clear()

        if self._away_task and not self._away_task.done():
            self._away_task.cancel()
        self._away_task = None

        _LOGGER.debug("PresenceManager: cancelled")
